### ISSUE TITLE
It seems that FM Generator cannot be used. NullPointerException

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#1008]
#### Prerequisitives
* **Eclipse Version:**  2020-03
* **FeatureIDE-Version:**  3.6.2
* **Git branch/Commit-ID:**  develop and master

### Issue description
`de.ovgu.featureide.fm.core.editing.evaluation.Generator.generateFeatureModel(long, int)`

`Exception in thread "main" java.lang.NullPointerException
	at de.ovgu.featureide.fm.core.editing.evaluation.Generator.generateFeatureDiagram(Generator.java:79)
	at de.ovgu.featureide.fm.core.editing.evaluation.Generator.generateFeatureModel(Generator.java:65)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.Main.main(Main.java:9)`

Previous line 78 returns null
`final IFeature parent = leaves.remove(parentIndex);`

**Comment by jabiercoding** [comment]
Adding this in line 74 of generateFeatureDiagram fix the NullPointerException
`		final IFeature c1 = factory.createFeature(fm, "C1");
		fm.getStructure().setRoot(c1.getStructure());
		fm.addFeature(c1);`
However, now there is another exception when creating the constraints in `de.ovgu.featureide.fm.core.editing.evaluation.Generator.generateConstraints(IFeatureModel, Random, int)`

`Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.ovgu.featureide.fm.core.AnalysesCollection$AnalysisWrapper.createNewAnalysis(AnalysesCollection.java:217)
	at de.ovgu.featureide.fm.core.AnalysesCollection$AnalysisWrapper.getResult(AnalysesCollection.java:185)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.isValid(FeatureModelAnalyzer.java:104)
	at de.ovgu.featureide.fm.core.editing.evaluation.Generator.generateConstraints(Generator.java:132)
	at de.ovgu.featureide.fm.core.editing.evaluation.Generator.generateFeatureModel(Generator.java:66)`

**Comment by tthuem** [comment]
Thanks for your report, we will have a look soon.

**Comment by Subaro** [comment]
The fix for the feature model generator is pending in #1072
