### ISSUE TITLE
"No fitting format found for file C:\..." when opening java file in FeatureIDE project.

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#1017]
How to reproduce:

1. load featureide example project helloworld-antenna

2. open the HelloWorld.java file

3. Check error log for errors. It should pop up every time you open the editor or save the file.

I'm not sure if this leads to any other errors, but it's odd. The bug happens on both develop and release3.6.

I've tried this with the munge helloworld and antenna helloworld examples.

```
de.ovgu.featureide.fm.core.ExtensionManager$NoSuchExtensionException: No fitting format found for file C:\Users\paula\Documents\Arbeit\runtime-FeatureIDETest\HelloWorld-Munge\src\HelloWorld.java
	at de.ovgu.featureide.fm.core.io.manager.AFileManager.detectFormat(AFileManager.java:226)
	at de.ovgu.featureide.fm.core.io.manager.AFileManager.init(AFileManager.java:197)
	at de.ovgu.featureide.fm.core.io.manager.FeatureModelManager.init(FeatureModelManager.java:88)
	at de.ovgu.featureide.fm.core.io.manager.AFileManager.getOrCreateInstance(AFileManager.java:133)
	at de.ovgu.featureide.fm.core.io.manager.FeatureModelManager.getInstance(FeatureModelManager.java:56)
	at de.ovgu.featureide.ui.views.collaboration.outline.FSTOutline.handleUpdate(FSTOutline.java:110)
	at de.ovgu.featureide.fm.ui.views.outline.custom.Outline$9.runInUIThread(Outline.java:480)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3537)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by PaulWestphal** [comment]
I have no idea what the intended behaviour is supposed to be. java files are never registered in the file manager because the ExtensionManager.getExtensions() does not have the .java format.

**Comment by PaulWestphal** [comment]
Maybe @skrieter could take a look at this. He seemed to know something about this two weeks ago.

**Comment by tthuem** [comment]
Only entry in error log. No actual misleading behavior visible.

**Comment by PaulWestphal** [comment]
The error comes from the FeatureIDE Outline, and it has to be open to reproduce this bug. But I've taken a closer look at the outline view and there doesn't seem to be anything wrong with it.

**Comment by tthuem** [comment]
Could be fixed with the new architecture. Check then.
