### ISSUE TITLE
Generating T-wise configurations with "Product Generator" fails for IncLing

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#1018]
#### Prerequisitives
* **FeatureIDE-Version:**  `release3.6 & config_generation`
* **Operating system:** `Win10`

### Issue description
When generating t-wise configuration for `Elevator-Antenna-v1.4` via the product generator dialogue with IncLing (t=2) the following error appears:

```
java.lang.ArrayIndexOutOfBoundsException: 73
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.PairWiseConfigurationGenerator.addRelation(PairWiseConfigurationGenerator.java:296)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.PairWiseConfigurationGenerator.findInvalid(PairWiseConfigurationGenerator.java:452)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.PairWiseConfigurationGenerator.generate(PairWiseConfigurationGenerator.java:837)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:71)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:1)
	at de.ovgu.featureide.fm.core.analysis.cnf.analysis.AbstractAnalysis.execute(AbstractAnalysis.java:82)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:53)
	at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator.execute(ACNFConfigurationGenerator.java:106)
	at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator.execute(ACNFConfigurationGenerator.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:44)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:122)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

```

I also tested five other examples and got always the same error.

**Comment by Subaro** [comment]
Bug was introduced in f8a36751282c671ee4d2d8b16ce263cef1dcecb1 as the plugin reference from apache.commons.math was removed.

**Comment by Subaro** [comment]
Fix (pull request) awaits review #1030

**Comment by Subaro** [comment]
Fix above was for #983, and thus, this issue is not resolved

**Comment by Subaro** [comment]
Not fixed

**Comment by h3ssto** [comment]
Is this applicable? https://bugs.eclipse.org/bugs/show_bug.cgi?id=471077

**Comment by skrieter** [comment]
Fixed
