### ISSUE TITLE
IllegalStateException when selecting false-optional feature in feature diagram

### ISSUE THREAD

**Issue by sjvie** [FeatureIDE/FeatureIDE#1027]
#### Prerequisitives
* **Eclipse Version:**  4.13
* **Git branch/Commit-ID:** develop / 8f048b58ec9654d277f8016d5159ec849d59158c

### Issue description
An unhandled loop exception (IllegalStateException) is thrown when selecting a false-optional feature with a warning. When the feature is selected and the feature model editor gets focused, an error dialog is shown. The following exception is thrown:
```
java.lang.IllegalStateException: Problem is satisfiable
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jMusExtractor.getMinimalUnsatisfiableSubsetIndexes(Sat4jMusExtractor.java:60)
	at org.prop4j.explain.solvers.impl.sat4j.Sat4jMusExtractor.getAllMinimalUnsatisfiableSubsetIndexes(Sat4jMusExtractor.java:82)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.mus.MusFalseOptionalFeatureExplanationCreator.getExplanation(MusFalseOptionalFeatureExplanationCreator.java:64)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.mus.MusFalseOptionalFeatureExplanationCreator.getExplanation(MusFalseOptionalFeatureExplanationCreator.java:1)
	at de.ovgu.featureide.fm.core.explanations.impl.composite.CompositeExplanationCreator.getExplanation(CompositeExplanationCreator.java:84)
	at de.ovgu.featureide.fm.core.AnalysesCollection.createExplanation(AnalysesCollection.java:413)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getFeatureExplanation(FeatureModelAnalyzer.java:581)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getExplanation(FeatureModelAnalyzer.java:527)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getExplanation(FeatureModelAnalyzer.java:514)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor.setActiveExplanation(FeatureDiagramEditor.java:470)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$3.runInUIThread(FeatureDiagramEditor.java:580)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

```

The problem is reproducible using this simple model:
![image](https://user-images.githubusercontent.com/35612644/82041453-7fbd3580-96a8-11ea-8a69-b9adc810d34a.png)

When `f1` is selected and the focus changes from another view back to the feature model editor, the error pop-up appears.

**Comment by sjvie** [comment]
The exception disappears after saving the model. Deleting the feature `f1` and creating a new feature with the same constraint recreates the error until the model is saved again.

**Comment by tthuem** [comment]
Is this enough related to the team project?

**Comment by Subaro** [comment]
This issue is produced by thge renaming manager and Node class.

@skrieter  Is it necessary to use the old names when creating a new variable? This results in old feature names being used for the explanations.
```
	public static String getVariable(IFeature feature) {
		return getVariable(feature, feature.getFeatureModel());
	}

	public static String getVariable(IFeature feature, IFeatureModel featureModel) {
		return getVariable(feature.getName(), featureModel);
	}

	public static String getVariable(String featureName, IFeatureModel featureModel) {
		return featureModel.getRenamingsManager().getOldName(featureName);
	}
```

I just replace the way nodes are created for explaining the defect. This solves the issue. However, maybe we should consider renaming the `getVariable` method as it is not clear when old or new names are used.
