### ISSUE TITLE
long Math.multiplyExact(long, int) is not available in Java 1.8

### ISSUE THREAD

**Issue by witschel** [FeatureIDE/FeatureIDE#1099]
### Issue description

You specify that Java 1.8 or higher is required. (Source: https://featureide.github.io/)

In the class BinomialCalculator.java (package de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.iterator) you are using the Method long Math.multiplyExact(long, int), which is not available in Java 1.8.

My current fix is: b = Math.multiplyExact(b, Long.valueOf(m)) / i;

**Comment by h3ssto** [comment]
`int` gets [implicitly converted](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.2) to `long`, where necessary. As the first parameter in the call (b) is of type `long` [`multiplyExactly(long, long)`](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#multiplyExact-long-long-) gets called and evaluated. The supplied `int` parameter is therein converted implicitly to `long`.

I cannot see the necessity to replace the implicit type cast by an explicit one. From my testing, the code runs flawless with `jdk8-openjdk`. Please note that `Long.valueOf(m)` is far more expensive than `(long) m` and both are unnecessary to convert from `int` to `long`.

**Comment by witschel** [comment]
System information:
OS: Windows 10
JRE: jdk1.8.0_261

I get the following error message:

Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.iterator.BinomialCalculator.binomial(BinomialCalculator.java:62)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.iterator.RandomPartitionSupplier.<init>(RandomPartitionSupplier.java:56)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.iterator.RandomPartitionSupplier.<init>(RandomPartitionSupplier.java:48)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.iterator.SingleIterator.<init>(SingleIterator.java:49)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.TWiseConfigurationGenerator.buildCombinations(TWiseConfigurationGenerator.java:243)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.twise.TWiseConfigurationGenerator.generate(TWiseConfigurationGenerator.java:194)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:71)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:39)
	at de.ovgu.featureide.fm.core.analysis.cnf.analysis.AbstractAnalysis.execute(AbstractAnalysis.java:84)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:53)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:41)
	at yasatest.YasaTest.main(YasaTest.java:29)

**Comment by h3ssto** [comment]
The problem lies within your 
> JRE: jdk1.8.0_261

The API in this part of the Java library was changed and it should work flawlessly under more recent version (tested under `openjdk version "1.8.0_275"`)
