### ISSUE TITLE
Runtime variability: Exception on every file save when PropertyManager is called with non-constant String

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1110]
_FeatureIDE 3.7,0_

In a project with runtime parameters, this minimum working example ...
![grafik](https://user-images.githubusercontent.com/4258713/117039763-6ffb8e80-ad09-11eb-9a66-ac4f3ab922f8.png)

produces the following error message on each build (and file save):
![grafik](https://user-images.githubusercontent.com/4258713/117039688-565a4700-ad09-11eb-98d6-713ce1896640.png)

Stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at de.ovgu.featureide.core.runtime.RuntimeParameters.setFeatureLocations(RuntimeParameters.java:486)
	at de.ovgu.featureide.core.runtime.RuntimeParameters.buildFSTModel(RuntimeParameters.java:110)
	at de.ovgu.featureide.core.runtime.RuntimeParameters.performFullBuild(RuntimeParameters.java:385)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

It seems that FeatureIDE tries to parse all code for calls to the PropertyManager, to detect invalid feature names. This only works correctly when a string constant is passed, however. This should be fixed so that we can check feature presence dynamically at runtime (of course, for that use case we cannot provide code assistance).

Another problem I noticed is that each save causes a `UI freeze of 3,0s`. This may also be related to the static code analysis, which may be implemented very inefficiently. Either we can improve the performance of this analysis or make it optional, because these UI lags make the IDE hard to use.

**Comment by ekuiter** [comment]
While opening another runtime variability project, I got a new error message with stack trace:
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList.sort(ArrayList.java:1752)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at de.ovgu.featureide.core.runtime.RuntimeParameters.setFeatureLocations(RuntimeParameters.java:505)
	at de.ovgu.featureide.core.runtime.RuntimeParameters.buildFSTModel(RuntimeParameters.java:110)
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.createDirectiveList(ColorAnnotationModel.java:334)
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.updateAnnotations(ColorAnnotationModel.java:291)
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.<init>(ColorAnnotationModel.java:143)
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.attach(ColorAnnotationModel.java:199)
	at de.ovgu.featureide.ui.editors.annotation.EditorTracker.annotateEditor(EditorTracker.java:146)
	at de.ovgu.featureide.ui.editors.annotation.EditorTracker.access$1(EditorTracker.java:143)
	at de.ovgu.featureide.ui.editors.annotation.EditorTracker$2.partActivated(EditorTracker.java:93)
	at org.eclipse.ui.internal.PartService$6.run(PartService.java:145)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.PartService.partActivated(PartService.java:142)
	at org.eclipse.ui.internal.WorkbenchPage$4.run(WorkbenchPage.java:4905)
	...
```
This is probably related to the issue above (but I cannot reproduce it).
