### ISSUE TITLE
AHEAD Composer: Cannot open JAK files with Jak editor

### ISSUE THREAD

**Issue by ekuiter** [FeatureIDE/FeatureIDE#1112]
*FeatureIDE 3.7.0, Eclipse with FeatureIDE, JDT, CDT, and AJDT*

I can't open any Jak files. This happens when I open a .jak file in the example project *HelloWorld-AHEAD*:

![grafik](https://user-images.githubusercontent.com/4258713/118393885-b7efaf00-b641-11eb-938f-4cbcc182364a.png)

Maybe I am missing some Eclipse packages. I installed the prepackaged FeatureIDE version from the website.

Exception details:

```
org.eclipse.core.runtime.CoreException: Plug-in de.ovgu.featureide.ui was unable to load class de.ovgu.featureide.ui.editors.JavaEditor.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
	...
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/ui/javaeditor/CompilationUnitEditor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:294)
	... 107 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor cannot be found by de.ovgu.featureide.ui_3.7.0.202010141034
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:464)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 122 more
```

![grafik](https://user-images.githubusercontent.com/4258713/118394002-64319580-b642-11eb-888b-198676b6d26d.png)

**Comment by h3ssto** [comment]
This has been already been fixed with #1096.
