### ISSUE TITLE
Yasa Product Generation throws NPE on different models

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#1118]
#### Prerequisitives
* **Eclipse Version:**  `org.eclipse.equinox.launcher_1.5.800.v20200727-1323`
* **FeatureIDE-Version:**  `3.7.0`
* **Operating system:** `linux, ubuntu 18.04`
* **Java runtime used to run eclipse:** `1.7`

### Issue description

On my ubuntu system, and in an newly created FeatureIDE project. When I start the product generation via the GUI context menu, configure the Yasa algorithm (default parameters) and use either the FeatureIDE model.xml (from the repo sources) or an arbitrary created model by me, for example [1], the following stacktrace shows up:

```
Exception in thread "Thread-45193" java.lang.NullPointerException
        at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator$Consumer.run(ACNFConfigurationGenerator.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Thats the following line.
https://github.com/FeatureIDE/FeatureIDE/blob/654b49526abf36971ada2ce346dd5890471b2dfd/plugins/de.ovgu.featureide.ui/src/de/ovgu/featureide/ui/actions/generator/configuration/ACNFConfigurationGenerator.java#L61

I don't think the NPE reported in #967 directly related.

As always, thank you for your work on the software :)

[1]: A root feature, with three mandatory childs. Each childs has 5 features and the child relationship is marked as OR.

**Comment by cpwnd** [comment]
Fixed it thanks!
