### ISSUE TITLE
Invocation of product generation via CLI tool results in ParserException

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#1120]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.7`
* **Git branch/Commit-ID:**  `654b49526abf36971ada2ce346dd5890471b2dfd`
* **Java compiler used to build the FeatureIDE plugin:** `11.0.11`

### Issue description

I tried to invoke the CLI tool. In order to do that, I build the sources of the core plugin, using the files of the above commit and the ant build command.
After successfully building the sources, I use a model.xml, e.g. the featuremodel of the FeatureIDE. The [listed formats](1) below the CLI command part in the wiki just state "FeatureIDE XML", so I don't know if it means both.
Either wich format I use, I get the following error:
```
$ java -jar jar/de.ovgu.featureide.lib.fm-v3.7.0.jar genconfig -a YASA -t 2 -fm /opt/Code/FeatureIDE/featuremodels/model.xml -o sample.csv 
[genconfig, -a, YASA, -t, 2, -fm, /opt/Code/FeatureIDE/featuremodels/model.xml, -o, sample.csv]
ERROR: Invalid problem format
java.text.ParseException: Invalid problem format
	at de.ovgu.featureide.fm.core.io.dimacs.DimacsReader.readProblem(DimacsReader.java:165)
	at de.ovgu.featureide.fm.core.io.dimacs.DimacsReader.read(DimacsReader.java:112)
	at de.ovgu.featureide.fm.core.io.dimacs.DimacsReader.read(DimacsReader.java:150)
	at de.ovgu.featureide.fm.core.io.dimacs.DIMACSFormatCNF.read(DIMACSFormatCNF.java:61)
	at de.ovgu.featureide.fm.core.io.dimacs.DIMACSFormatCNF.read(DIMACSFormatCNF.java:43)
	at de.ovgu.featureide.fm.core.io.IPersistentFormat.read(IPersistentFormat.java:60)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.parse(SimpleFileHandler.java:255)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.read(SimpleFileHandler.java:212)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.load(SimpleFileHandler.java:120)
	at de.ovgu.featureide.fm.core.cli.ConfigurationGenerator.run(ConfigurationGenerator.java:82)
	at de.ovgu.featureide.fm.core.cli.FeatureIDECLI.main(FeatureIDECLI.java:60)
java.text.ParseException: Invalid problem format
```

I also get a parser exception when I use a dimacs file.

[1]: https://github.com/FeatureIDE/FeatureIDE/blob/654b49526abf36971ada2ce346dd5890471b2dfd/plugins/de.ovgu.featureide.fm.core/library/README.md#supported-input-formats

Hope this helps!

**Comment by cpwnd** [comment]
Thank you for the quick response! Fixed it.
