### ISSUE TITLE
Adding Cross-Tree-Constraints causes Exceptions in the Feature Model Edits View

### ISSUE THREAD

**Issue by bjthehun** [FeatureIDE/FeatureIDE#1185]
#### Prerequisitives
* **Eclipse Version:** 2021-06 (4.20)
* **FeatureIDE-Version:**  3.7.2 (Base Version)
* **Operating system:** Ubuntu 21.04
* **Java runtime used to run eclipse:** OpenJDK 64-Bit Server VM 16.0.1
* **FeatureIDE Composer:** Feature Modelling
* **Git branch/Commit-ID:** 5f71ee16f26955647f746730c636a335900fe56f
* **Java compiler used to build the FeatureIDE plugin:** Compliance for Java 1.8

### Issue description
- [ ] Single-Feature Cross-Tree-Constraints in a Feature Model cause Exceptions in the Feature Model Edits View about the missing feature `True`, such as:

```
java.lang.Exception
	at de.ovgu.featureide.fm.core.EclipseLogger.logWarning(EclipseLogger.java:51)
	at de.ovgu.featureide.fm.core.Logger.logWarning(Logger.java:36)
	at de.ovgu.featureide.fm.core.io.Problem.<init>(Problem.java:93)
	at de.ovgu.featureide.fm.core.io.Problem.<init>(Problem.java:66)
	at de.ovgu.featureide.fm.core.configuration.DefaultFormat.read(DefaultFormat.java:95)
	at de.ovgu.featureide.fm.core.editing.ExampleCalculator.nextExample(ExampleCalculator.java:117)
	at de.ovgu.featureide.fm.core.editing.ModelComparator.calculateExample(ModelComparator.java:237)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ExampleParent.initChildren(ExampleParent.java:89)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.TreeParent.getChildren(TreeParent.java:56)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.TreeObject.set(TreeObject.java:68)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ViewContentProvider.setHeadAndExamples(ViewContentProvider.java:301)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ViewContentProvider.calculateContent(ViewContentProvider.java:260)
	at de.ovgu.featureide.fm.ui.views.FeatureModelEditView$5$1.run(FeatureModelEditView.java:322)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

#### Steps to Reproduce:
1. In the `Universal-Variability-Language-Multi` example, open the `OperatingSystem.uvl` and `Server.uvl` feature models.
2. Add for the `Server` model the constraint `os.Debian`.
3. Trigger the Edit View to refresh, for example by selecting the tab for `OperatingSystem`, then for `Server` again.

- [ ] Adding a constraint that voids the Feature Model similiary causes exceptions for the Feature Model Edit View, such as:
```
de.ovgu.featureide.fm.core.analysis.cnf.solver.RuntimeContradictionException: org.sat4j.specs.ContradictionException: Creating Empty clause ?
	at de.ovgu.featureide.fm.core.analysis.cnf.solver.SimpleSatSolver.addClause(SimpleSatSolver.java:95)
	at de.ovgu.featureide.fm.core.analysis.cnf.solver.SimpleSatSolver.addClauses(SimpleSatSolver.java:120)
	at de.ovgu.featureide.fm.core.analysis.cnf.solver.SimpleSatSolver.addClauses(SimpleSatSolver.java:109)
	at de.ovgu.featureide.fm.core.analysis.cnf.manipulator.remove.CNFSlicer.firstRedundancyCheck(CNFSlicer.java:402)
	at de.ovgu.featureide.fm.core.analysis.cnf.manipulator.remove.CNFSlicer.manipulate(CNFSlicer.java:175)
	at de.ovgu.featureide.fm.core.analysis.cnf.manipulator.AbstractManipulator.execute(AbstractManipulator.java:47)
	at de.ovgu.featureide.fm.core.analysis.cnf.manipulator.AbstractManipulator.execute(AbstractManipulator.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:53)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:41)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.SlicedCNFCreator.create(SlicedCNFCreator.java:48)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.SlicedCNFCreator.create(SlicedCNFCreator.java:1)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.ACreator.get(ACreator.java:44)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.FeatureModelFormula.getElement(FeatureModelFormula.java:61)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationPropagator.getSolver(ConfigurationPropagator.java:561)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationPropagator.getSolverForCurrentConfiguration(ConfigurationPropagator.java:534)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationPropagator$CountSolutionsMethod.execute(ConfigurationPropagator.java:172)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationPropagator$CountSolutionsMethod.execute(ConfigurationPropagator.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:53)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:41)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationAnalyzer.number(ConfigurationAnalyzer.java:112)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ViewContentProvider.calculateNumberOfVariants(ViewContentProvider.java:467)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ViewContentProvider.access$1(ViewContentProvider.java:450)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ViewContentProvider$4.run(ViewContentProvider.java:415)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.sat4j.specs.ContradictionException: Creating Empty clause ?
	at org.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at org.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at org.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at org.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at de.ovgu.featureide.fm.core.analysis.cnf.solver.SimpleSatSolver.addClause(SimpleSatSolver.java:93)
	... 23 more
```

#### Steps to Reproduce:
1. In the same feature model, add the contradictory constraint `Logging and not Logging`.

**Comment by Rahel12342** [comment]
I am not able to reproduce any of these two cases.

**Comment by tthuem** [comment]
The first issue is not an issue.

The second needs to be investigated.

**Comment by Rahel12342** [comment]
I am not able to reproduce this issue (neither with a .xml model nor with Universal-Variability-Language or Universal-Variability-Language-Multi.
