### ISSUE TITLE
Broken FeatureIDE Example FeatureAttributes

### ISSUE THREAD

**Issue by wurstbroteater** [FeatureIDE/FeatureIDE#1383]
#### Prerequisitives
* **Eclipse Version:**  `v3.9.0`
* **FeatureIDE-Version:**  `v4.2.0`
* **Operating system:** `Windows 11`
* **Java runtime used to run eclipse:** `jdk-11.0.10.9-hotspot`
* **FeatureIDE Composer:**
* **Git branch/Commit-ID:** 

### Issue description
For the FeatureIDE example project 'FeatureAttributes', the first problem is that the libraries linked in the Build Path are wrong. Linked libraries are in version 3.9.0 but only libraries in version 3.8.3 are present  (as in #1375). The suggested workaround is to replace the old libraries with the new one.
In both cases (using library in version 3.8.3 or 3.9.0) the code still has an error. The error is the call `att.recurseAttribute(feat);` in method `addAttribute(IFeature feat, IFeatureAttribute att)`. In both versions, the object `att` does not provide this method and ends with:
```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method recurseAttribute(IFeature) is undefined for the type IFeatureAttribute

	at de.ovgu.featureide.examples.featureattributes.FeatureAttributes.addAttribute(FeatureAttributes.java:113)
	at de.ovgu.featureide.examples.featureattributes.FeatureAttributes.addAttributeValues(FeatureAttributes.java:71)
	at de.ovgu.featureide.examples.featureattributes.FeatureAttributes.main(FeatureAttributes.java:50)
```
Related to #1380 and #1375

**Comment by skrieter** [comment]
Duplicate. See #1375
