### ISSUE TITLE
Unhandled exception for FeatureC++ if gcc is not installed

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#195]
Adding the hello world example for FeatureC++ leads to the following exception (multiple times) if gcc is not installed:

```
java.io.IOException: Cannot run program "gcc": Launching failed
    at org.eclipse.cdt.utils.spawner.Spawner.exec(Spawner.java:349)
    at org.eclipse.cdt.utils.spawner.Spawner.<init>(Spawner.java:91)
    at org.eclipse.cdt.utils.spawner.ProcessFactory.exec(ProcessFactory.java:91)
    at org.eclipse.cdt.core.CommandLauncher.execute(CommandLauncher.java:194)
    at org.eclipse.cdt.internal.core.BuildRunnerHelper.build(BuildRunnerHelper.java:263)
    at org.eclipse.cdt.make.internal.core.scannerconfig2.DefaultRunSIProvider.invokeProvider(DefaultRunSIProvider.java:144)
    at org.eclipse.cdt.build.internal.core.scannerconfig.jobs.CfgSCJobsUtil$1.run(CfgSCJobsUtil.java:94)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.runtime.Platform.run(Platform.java:867)
    at org.eclipse.cdt.build.internal.core.scannerconfig.jobs.CfgSCJobsUtil.getProviderScannerInfo(CfgSCJobsUtil.java:105)
    at org.eclipse.cdt.build.core.scannerconfig.ScannerConfigBuilder.build(ScannerConfigBuilder.java:206)
    at org.eclipse.cdt.build.internal.core.scannerconfig.CfgDiscoveredPathManager.loadPathInfo(CfgDiscoveredPathManager.java:298)
    at org.eclipse.cdt.build.internal.core.scannerconfig.CfgDiscoveredPathManager.getDiscoveredInfo(CfgDiscoveredPathManager.java:177)
    at org.eclipse.cdt.managedbuilder.internal.dataprovider.ProfileInfoProvider.getEntryValues(ProfileInfoProvider.java:65)
    at org.eclipse.cdt.managedbuilder.internal.dataprovider.BuildEntryStorage.getDiscoveredEntries(BuildEntryStorage.java:200)
    at org.eclipse.cdt.managedbuilder.internal.dataprovider.BuildEntryStorage.putEntriesToLevel(BuildEntryStorage.java:190)
    at org.eclipse.cdt.core.settings.model.util.AbstractEntryStorage.initCache(AbstractEntryStorage.java:71)
    at org.eclipse.cdt.core.settings.model.util.AbstractEntryStorage.getEntries(AbstractEntryStorage.java:34)
    at org.eclipse.cdt.managedbuilder.internal.dataprovider.BuildLanguageData.getEntries(BuildLanguageData.java:161)
    at org.eclipse.cdt.core.settings.model.extension.impl.CDefaultLanguageData.getEntriesToCopy(CDefaultLanguageData.java:101)
    at org.eclipse.cdt.core.settings.model.extension.impl.CDefaultLanguageData.createStore(CDefaultLanguageData.java:92)
    at org.eclipse.cdt.core.settings.model.extension.impl.CDefaultLanguageData.copySettingsFrom(CDefaultLanguageData.java:85)
    at org.eclipse.cdt.internal.core.settings.model.CLanguageSettingCache.copySettingsFrom(CLanguageSettingCache.java:47)
    at org.eclipse.cdt.internal.core.settings.model.CLanguageSettingCache.<init>(CLanguageSettingCache.java:36)
    at org.eclipse.cdt.internal.core.settings.model.CFolderDescriptionCache.copyLanguageData(CFolderDescriptionCache.java:79)
    at org.eclipse.cdt.core.settings.model.extension.impl.CDefaultFolderData.copyDataFrom(CDefaultFolderData.java:56)
    at org.eclipse.cdt.internal.core.settings.model.CFolderDescriptionCache.<init>(CFolderDescriptionCache.java:38)
    at org.eclipse.cdt.internal.core.settings.model.CConfigurationDescriptionCache.copyFolderData(CConfigurationDescriptionCache.java:235)
    at org.eclipse.cdt.core.settings.model.extension.impl.CDefaultConfigurationData.copySettingsFrom(CDefaultConfigurationData.java:113)
    at org.eclipse.cdt.internal.core.settings.model.CConfigurationDescriptionCache.loadData(CConfigurationDescriptionCache.java:150)
    at org.eclipse.cdt.internal.core.settings.model.CProjectDescription.loadDatas(CProjectDescription.java:196)
    at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage.loadProjectDescription(XmlProjectDescriptionStorage.java:500)
    at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage.getProjectDescription(XmlProjectDescriptionStorage.java:237)
    at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescriptionInternal(CProjectDescriptionManager.java:437)
    at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:419)
    at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:413)
    at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:406)
    at org.eclipse.cdt.internal.core.model.CProject.computeSourceRoots(CProject.java:585)
    at org.eclipse.cdt.internal.core.model.CProject.computeChildren(CProject.java:606)
    at org.eclipse.cdt.internal.core.model.CProject.buildStructure(CProject.java:570)
    at org.eclipse.cdt.internal.core.model.Openable.generateInfos(Openable.java:273)
    at org.eclipse.cdt.internal.core.model.CElement.openWhenClosed(CElement.java:427)
    at org.eclipse.cdt.internal.core.model.CElement.getElementInfo(CElement.java:305)
    at org.eclipse.cdt.internal.core.model.CElement.getElementInfo(CElement.java:295)
    at org.eclipse.cdt.internal.core.model.Parent.getChildren(Parent.java:55)
    at org.eclipse.cdt.internal.core.model.CModelManager.create(CModelManager.java:290)
    at org.eclipse.cdt.internal.core.model.CModelManager.create(CModelManager.java:267)
    at org.eclipse.cdt.internal.core.model.DeltaProcessor.createElement(DeltaProcessor.java:87)
    at org.eclipse.cdt.internal.core.model.DeltaProcessor.traverseDelta(DeltaProcessor.java:453)
    at org.eclipse.cdt.internal.core.model.DeltaProcessor.traverseDelta(DeltaProcessor.java:471)
    at org.eclipse.cdt.internal.core.model.DeltaProcessor.processResourceDelta(DeltaProcessor.java:433)
    at org.eclipse.cdt.internal.core.model.CModelManager.resourceChanged(CModelManager.java:900)
    at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
    at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
    at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:378)
    at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1498)
    at org.eclipse.core.internal.resources.Resource.delete(Resource.java:831)
    at org.eclipse.core.internal.resources.Resource.delete(Resource.java:769)
    at de.ovgu.featureide.featurecpp.FeatureCppComposer.buildFSTModel(FeatureCppComposer.java:239)
    at de.ovgu.featureide.featurecpp.FeatureCppComposer.initialize(FeatureCppComposer.java:98)
    at de.ovgu.featureide.core.internal.FeatureProject.getComposer(FeatureProject.java:1067)
    at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:342)
    at de.ovgu.featureide.core.internal.FeatureProject.<init>(FeatureProject.java:301)
    at de.ovgu.featureide.core.CorePlugin.addProject(CorePlugin.java:206)
    at de.ovgu.featureide.core.CorePlugin.addProjects(CorePlugin.java:620)
    at de.ovgu.featureide.core.CorePlugin$3.run(CorePlugin.java:591)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Instead, a single problem marker should be added to the project instead.

**Comment by tthuem** [comment]
@AlexanderKnueppel As I guess that you have not installed gcc... could you please try to reproduce the problem? If you cannot reproduce it, we can probably close it, as it might have been fixed in the meantime.

**Comment by AlexanderKnueppel** [comment]
Exceptions still remain with the current version:

![image](https://cloud.githubusercontent.com/assets/263321/17894232/ed701020-6948-11e6-9b33-70733faa0afc.png)

**Comment by Kogoro** [comment]
I think we can close this issue as the errors are created by the CDT plugin at the building phase.
Error markers for missing g++ and gcc are created and should guide the user.
![unbenannt4](https://user-images.githubusercontent.com/8019776/28848350-e13df870-7712-11e7-9929-28cffae0a018.PNG)
