### ISSUE TITLE
[MPL] working with test project "MPLChatTest"

### ISSUE THREAD

**Issue by anb0s** [FeatureIDE/FeatureIDE#220]
I've started to play with MPL functionality in FeatureIDE. See issue  #123 comment from RSchroeter:
...
In the current version of FeatureIDE it is possible to create some new model files in a (sub) directory. Afterwards, it is possible to reference these model artifacts out of the main model (project root). This functionality is only available, if the project is a mutli software product line (MPL) project. Therefore, it is possible to convert an ordinary FeatureIDE project to an MPL project (FeatureIDE -> Convert to Multi Software Product Line). 
...

My System:
Eclipse Luna SR2 4.4.2 (32Bit)
Windows 7 (64Bit)
JDK / JRE 1.8.0_31 (32Bit)
FeatureIDE + Feature Modeling (only, no other FIDE plugins) 2.7.2.201503021452

First i will start with sample project "MPLChatTest" from RScroeter. 

## Open the project MPLChatTest --> error message: ##
...
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.package.cpp.product

org.eclipse.core.jobs
Error
Tue Mar 03 16:48:24 CET 2015
An internal error occurred during: "Load Model".

java.lang.NullPointerException
	at de.ovgu.featureide.core.internal.FeatureProject$5.run(FeatureProject.java:923)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
...

## Try to open project preferences "FeatureIDE + Feature Project" --> error message ##

![featureide-mpl-error-in-project-properties](https://cloud.githubusercontent.com/assets/95811/6465922/68c3c6d2-c1c4-11e4-8807-3ed0dcba8523.png)

...
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.cpp.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.package.cpp.product

org.eclipse.jface
Error
Tue Mar 03 16:50:10 CET 2015
Problems occurred when invoking code from plug-in: "org.eclipse.jface".

java.lang.NullPointerException
	at de.ovgu.featureide.core.propertypage.FeatureProjectPropertyPage.createContents(FeatureProjectPropertyPage.java:139)
	at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:233)
	at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1537)
	at org.eclipse.jface.preference.PreferenceDialog$13.run(PreferenceDialog.java:1289)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1281)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:699)
	at org.eclipse.jface.preference.PreferenceDialog$9$1.run(PreferenceDialog.java:730)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.preference.PreferenceDialog$9.selectionChanged(PreferenceDialog.java:725)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:876)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:873)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1217)
	at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1243)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
	at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
	at org.eclipse.jface.util.OpenStrategy$1$2.run(OpenStrategy.java:440)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4147)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:160)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
...

## Open "mpl.velvet" file with FIDE and want to set other layout --> no menue entries like "Set Layout", "Hide Legend" or "Export As" ##

![featureide-mpl-missing-menue-entries](https://cloud.githubusercontent.com/assets/95811/6466147/ee3180f6-c1c5-11e4-8eb6-3145d366bc8a.png)

**Comment by anb0s** [comment]
I've installed nightly build 2.7.3.201503120400 and FeatureHouse.

Now "Set Layout" menue is there and works, but the settings are not persistent --> reopen velvet model and the layout is the default one. The new menue "Set Name Type" works as expected and is persistent.

The exception in preference dialog is still there.

Thanks!

**Comment by anb0s** [comment]
The menue "Create Constraint" is not there, but manual constraints in velvet file are working as expected.

**Comment by tthuem** [comment]
@RSchroeter What are your thoughts on this issue?

**Comment by RSchroeter** [comment]
We fixed some bugs and improved the representation of MPL models. For instance, 
- Only layout changes are allowed in the DiagramEditor (no changes of constraints and features)
- The switch between long and short names is now an layout change
- We removed entries in the preference dialog
- Layout changes does cause a dirty-editor state (the textual represention of the model is stable)

**Comment by anb0s** [comment]
Thanks!

I've verified my test model with "  Feature Modeling (required)	3.0.1.201605191759	"
- no exception in preference dialog --> OK
- set layout is working and is persistent now --> OK
- short names are not working; editor shows still the long names and also is not dirty -> NOT OK

![image](https://cloud.githubusercontent.com/assets/95811/16868889/56d0e906-4a7a-11e6-8034-908985705a07.png)

**Comment by tthuem** [comment]
André, thanks for your fast review! Reimar, shall we move it to the hotfix version in August?

**Comment by RSchroeter** [comment]
We investigated our solution again and we think it works. However, we assume that your Feature Modeling version 3.0.1.201605191759 is an old version. You can find our new solution in the nightly builds and in the develop branch. If there is still an error, please create a new issue. Thank you for your review!

**Comment by anb0s** [comment]
Thanks, but the version 3.0.1.201605191759 is the last one installed from the know update site: http://featureide.cs.ovgu.de/update/v3/

**Comment by anb0s** [comment]
Ok, tried the nightly build version:   Feature Modeling 3.0.1.201607200400

- [ ] the short names are now there --> OK
- [ ] but the names are not right, see screenshot above "Security_S7P_Repository.CSI.CSI_HARDWARE" is now just "Security_S7P_Repository._HARDWARE" the substring in name "CSI.CSI" is not shown:
![image](https://cloud.githubusercontent.com/assets/95811/16986959/c4c10352-4e89-11e6-8313-5aea9fd621a7.png)
the same for short names:
![image](https://cloud.githubusercontent.com/assets/95811/16987039/54e68056-4e8a-11e6-9e1c-b945c2a85a48.png)
