### ISSUE TITLE
Compilation problems with AspectJ's Telecom example

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#338]
#### Prerequisitives
* **Eclipse Version:**  Eclipse 4.5.2 Platform 64bit
* **FeatureIDE-Version:**  FeatureIDE v3.0.0
* **Operating system:** Windows 10 
* **Java runtime used to run eclipse:** 1.8.0_77
* **FeatureIDE Composer:** MPL-FH-Java?
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/d943a2e1e0e5bab1dd36d8f0992ef2fcf073fd15

### Issue description
Importing "Telecom Example-AspectJ" from the FeatureIDE examples leads to compilation errors. It would be good if we could fix the code or the feature model to avoid those problems.

![zwischenablage-4](https://cloud.githubusercontent.com/assets/5330357/14670123/14cbf086-06ec-11e6-8e92-5dfacfebd287.jpg)

Alex, this is not urgent, but could you have a look for an easy way to fix that, which still preserves some variability?

**Comment by tthuem** [comment]
Also, it would be good if we can prevent the problem marker "OK" assigned to each FeatureIDE project with AspectJ composer. If this is not due to FeatureIDE (but AJDT), we could still remove exactly this problem marker to avoid confusion.

![zwischenablage-5](https://cloud.githubusercontent.com/assets/5330357/14670320/dc3755ac-06ec-11e6-8482-58e6e1689cca.jpg)

**Comment by AlexanderKnueppel** [comment]
I've updated the example so far, but when I click on an aspect (and at the beginning as well), I get a NullPoitnerException:
![featureide_error](https://cloud.githubusercontent.com/assets/263321/15359927/c462e1c8-1d0b-11e6-9d2d-89e00a7ba1c8.png)

If it is not only me, I'll investigate it.

Also, do we want to remove the marker completely, or just replace it with another one (an information marker for example, as seen on the image above)?

**Comment by tthuem** [comment]
It is likely that the NullPointer comes from AspectJ and is due to the fact that the aspect is excluded from the build path. In that case we cannot fix it. Alex, could you please upload the stack trace?

**Comment by AlexanderKnueppel** [comment]
stack trace when clicking on a *.as excluded from the build path is as follows:
<details> 
  <summary>Click me</summary>
<pre><code>!ENTRY org.eclipse.jface 4 2 2016-05-20 11:14:27.053
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at de.ovgu.featureide.ui.projectExplorer.ProjectExplorerLabelProvider.getColors(ProjectExplorerLabelProvider.java:187)
	at de.ovgu.featureide.ui.projectExplorer.ProjectExplorerLabelProvider.getPackageColors(ProjectExplorerLabelProvider.java:210)
	at de.ovgu.featureide.ui.projectExplorer.ProjectExplorerLabelProvider.getImage(ProjectExplorerLabelProvider.java:126)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateCommonLabelProvider.getImage(SafeDelegateCommonLabelProvider.java:107)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.findImage(NavigatorContentServiceLabelProvider.java:199)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getColumnImage(NavigatorContentServiceLabelProvider.java:107)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getImage(NavigatorContentServiceLabelProvider.java:99)
	at org.eclipse.ui.internal.navigator.NavigatorDecoratingLabelProvider$StyledLabelProviderAdapter.getImage(NavigatorDecoratingLabelProvider.java:57)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getImage(DelegatingStyledCellLabelProvider.java:195)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getImage(DecoratingStyledCellLabelProvider.java:173)
	at org.eclipse.ui.navigator.CommonNavigatorManager.updateStatusBar(CommonNavigatorManager.java:316)
	at org.eclipse.ui.navigator.CommonNavigatorManager$1.selectionChanged(CommonNavigatorManager.java:75)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:877)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:874)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1243)
	at org.eclipse.ui.navigator.CommonViewer.handlePostSelect(CommonViewer.java:455)
	at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1269)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
	at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
	at org.eclipse.jface.util.OpenStrategy$1$2.run(OpenStrategy.java:440)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)</code></pre>
</details>

**Comment by tthuem** [comment]
@meinicke Could you please have a look at this?

**Comment by meinicke** [comment]
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/371101515e88173b29fe72f6eb6bfde3f0d7d2ac

**Comment by tthuem** [comment]
Alex, as discussed today the problem marker OK can be removed completely.
