### ISSUE TITLE
Exception caused while switching the cofiguration file

### ISSUE THREAD

**Issue by andykenner** [FeatureIDE/FeatureIDE#349]
#### Prerequisitives
* **Eclipse Version:**  `4.5.2`
* **FeatureIDE-Version:**  `3.0.0`
* **Operating system:** `Windows 7`
* **Java runtime used to run eclipse:** `JavaSE-1.7 (jre1.8.0_91)`
* **FeatureIDE Composer:** `FeatureHouse (JUnit_Example)`
* **Git branch/Commit-ID:**  `develop`
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
An exception is caused while opening the context menu to set a configuration file as current (Right-Click on a configuration)
Steps to reproduce:
* double click a on the configuration file in package explorer. it does not matter, whether its opened already
* and then right-click on the configuration in package explorer
* the action set as current configuration does not work in this situation, no reaction/no feedback

It does not happen if you don't double click the configuration in the first step

I get the following exception:

!MESSAGE Plug-in "de.ovgu.featureide.ui" was unable to instantiate class "de.ovgu.featureide.ui.actions.DynamicProfileMenu".
!STACK 0
java.lang.NullPointerException
	at de.ovgu.featureide.ui.actions.DynamicProfileMenu.getCurrentFeatureProject(DynamicProfileMenu.java:157)
	at de.ovgu.featureide.ui.actions.DynamicProfileMenu.<init>(DynamicProfileMenu.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at ...

**Comment by pinnecke** [comment]
Can reproduce it. Seems broken since we introduce the new popup as submenu for these entries (i.e., since somewhere around "set as active" was moved into a sub menu). Before this change, it worked as expected.

**Comment by Kogoro** [comment]
With the latest nightly build, I don't get the error message, but the configuration can not be changed. So this issue still exists.

**Comment by tthuem** [comment]
Seems to be urgent for our SPLC tutorial. Jens, please have a look or assign someone else. Thanks!
