### ISSUE TITLE
NullPointerException with non default project location

### ISSUE THREAD

**Issue by jabiercoding** [FeatureIDE/FeatureIDE#350]
#### Prerequisitives
* **Eclipse Version:**  4.5.1
* **FeatureIDE-Version:**  3.0.0
* **Operating system:** windows
* **Java runtime used to run eclipse:** 1.8
* **FeatureIDE Composer:** `Add text here (optional, leave blank if not needed)`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `Add text here (optional, leave blank if not needed)`

### Issue description
Create a project with a composer and change the default project location. Then click on finish. A null pointer exception window appears and this is what you get in the console. I ignore the consequences of this, but I am experiencing important issues when I put my project in git (location change).

```
java.lang.NullPointerException
	at de.ovgu.featureide.fm.core.color.FeatureColorManager.getProject(FeatureColorManager.java:296)
	at de.ovgu.featureide.fm.core.color.FeatureColorManager.getCurrentColorScheme(FeatureColorManager.java:141)
	at de.ovgu.featureide.fm.core.color.FeatureColorManager.getCurrentColorScheme(FeatureColorManager.java:134)

```

**Comment by jabiercoding** [comment]
I cannot reproduce it again using the Feature IDE develop branch... so I close it.
