### ISSUE TITLE
ClassCastException with AST when generating Feature Model to Metaproducts.

### ISSUE THREAD

**Issue by guilhermejcgois** [FeatureIDE/FeatureIDE#355]
#### Prerequisitives
* **Eclipse Version:**  `Mars.2 Release (4.5.2)`
* **FeatureIDE-Version:**  `3.0.0.201604201`
* **Operating system:** `Fedora 23`
* **Java runtime used to run eclipse:** `jdk1.8.0_73`
* **FeatureIDE Composer:** `FeatureHouse`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When I do a build of metaproducts for my SPL to generate the feature model, I get this exception and stacktrace:
`java.lang.ClassCastException: AST.CONSTANT_NameAndType_Info cannot be cast to AST.CONSTANT_Class_Info
	at AST.BytecodeParser.parseThisClass(BytecodeParser.java:440)
	at AST.BytecodeParser.parseTypeDecl(BytecodeParser.java:407)
	at AST.BytecodeParser.parse(BytecodeParser.java:334)
	at AST.BytecodeParser.parse(BytecodeParser.java:304)
	at AST.Attributes$TypeAttributes.innerClasses(Attributes.java:415)
	at AST.Attributes$TypeAttributes.processAttribute(Attributes.java:319)
	at AST.Attributes.attributes(Attributes.java:64)
	at AST.Attributes$TypeAttributes.<init>(Attributes.java:310)
	at AST.BytecodeParser.parse(BytecodeParser.java:340)
	at AST.BytecodeParser.read(BytecodeParser.java:30)
	at AST.PathPart.getCompilationUnit(PathPart.java:118)
	at AST.Program.getCompilationUnit(Program.java:266)
	at AST.Program.lookupType_compute(Program.java:1459)
	at AST.Program.lookupType(Program.java:1440)
	at AST.Program.Define_TypeDecl_lookupType(Program.java:1998)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.ASTNode.Define_TypeDecl_lookupType(ASTNode.java:2727)
	at AST.Expr.lookupType(Expr.java:1363)
	at AST.TypeAccess.decls_compute(TypeAccess.java:490)
	at AST.TypeAccess.decls(TypeAccess.java:479)
	at AST.TypeAccess.decl_compute(TypeAccess.java:527)
	at AST.TypeAccess.decl(TypeAccess.java:517)
	at AST.TypeAccess.type_compute(TypeAccess.java:704)
	at AST.TypeAccess.type(TypeAccess.java:697)
	at AST.SingleTypeImportDecl.importedTypes_compute(SingleTypeImportDecl.java:183)
	at AST.SingleTypeImportDecl.importedTypes(SingleTypeImportDecl.java:174)
	at AST.CompilationUnit.importedTypes_compute(CompilationUnit.java:808)
	at AST.CompilationUnit.importedTypes(CompilationUnit.java:798)
	at AST.CompilationUnit.refined_TypeScopePropagation_CompilationUnit_Child_lookupType_String(CompilationUnit.java:703)
	at AST.CompilationUnit.Define_SimpleSet_lookupType(CompilationUnit.java:1210)
	at AST.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:2733)
	at AST.TypeDecl.lookupType(TypeDecl.java:7010)
	at AST.TypeDecl.Define_SimpleSet_lookupType(TypeDecl.java:7552)
	at AST.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:2733)
	at AST.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:2733)
	at AST.ASTNode.Define_SimpleSet_lookupType(ASTNode.java:2733)
	at AST.Expr.lookupType(Expr.java:1374)
	at AST.ClassInstanceExpr.Define_SimpleSet_lookupType(ClassInstanceExpr.java:1333)
	at AST.ParTypeAccess.Define_SimpleSet_lookupType(ParTypeAccess.java:414)
	at AST.Expr.lookupType(Expr.java:1374)
	at AST.TypeAccess.decls_compute(TypeAccess.java:488)
	at AST.TypeAccess.decls(TypeAccess.java:479)
	at AST.TypeAccess.decl_compute(TypeAccess.java:527)
	at AST.TypeAccess.decl(TypeAccess.java:517)
	at AST.TypeAccess.type_compute(TypeAccess.java:704)
	at AST.TypeAccess.type(TypeAccess.java:697)
	at AST.ParTypeAccess.genericDecl_compute(ParTypeAccess.java:362)
	at AST.ParTypeAccess.genericDecl(ParTypeAccess.java:356)
	at AST.ParTypeAccess.type_compute(ParTypeAccess.java:336)
	at AST.ParTypeAccess.type(ParTypeAccess.java:328)
	at AST.ClassInstanceExpr.type_compute(ClassInstanceExpr.java:1140)
	at AST.ClassInstanceExpr.type(ClassInstanceExpr.java:1133)
	at AST.FieldDeclaration.splTypeCheck(FieldDeclaration.java:546)
	at AST.ASTNode.collectSplErrors(ASTNode.java:689)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.ASTNode.collectSplErrors(ASTNode.java:691)
	at AST.Program.splErrorCheck(Program.java:719)
	at fuji.Main.typecheckAST(Main.java:443)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.runFuji(FeatureHouseComposer.java:722)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer.access$2(FeatureHouseComposer.java:706)
	at de.ovgu.featureide.featurehouse.FeatureHouseComposer$3.work(FeatureHouseComposer.java:686)
	at de.ovgu.featureide.fm.core.job.AStoppableJob$InnerThread.run(AStoppableJob.java:54)`

This should happen? When I reopen the EclipseIDE, my project has checked the box for "Build Metaproducts" options in FeatureIDE -> FeatureHouse -> Build Metaproduct and generated FM.FeatureModel.java. I guess that something is wrong...

The project that I got this exception is [this](https://github.com/guilhermejcgois/e-MuseumLPS/tree/featurehouse-experiment).

**Comment by tthuem** [comment]
Thanks for your bug report. Sounds like an annoying error. Does it work as expected after restarting Eclipse?

**Comment by tthuem** [comment]
Thanks, Jens!

Guilherme, we just rebuild FeatureIDE on our nightly builds update site. It would be great if you could update to the most recent version and let us know if there are further problems. Thanks.

**Comment by guilhermejcgois** [comment]
When I restart, all works, but I can't resolve this import:
`import gov.nasa.jpf.vm.Verify;`
But I guess that is not a problem with FeatureIDE itself, except if the library with this jar should be added to the project.

I will check the update. U r welcome.

**Comment by meinicke** [comment]
In the project properties/FeatureIDE you can select different types of metaproducts, depending on what you need.

**Comment by guilhermejcgois** [comment]
Sorry guys, but here still gives error...
I tried to modify my model, but always gives error.
Could be the error my fault with the project? The source generated by the features always goes inside 'default' package, what leaves in error on package declaration.

**Comment by meinicke** [comment]
I checked it out, it is actually a bug (unrelated to this issue though).
I will have a look at is om Monday.

**Comment by meinicke** [comment]
fixed in https://github.com/FeatureIDE/FeatureIDE/commit/c8ca599b7ba110b4e254b837d9ba848182f20790
