### ISSUE TITLE
Selecting several features with the same parent and create a new feature above does not work anymore

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#427]
```
java.lang.RuntimeException: Create compound operator for multiple selected features is not supported.
    at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.CreateCompoundAction.run(CreateCompoundAction.java:86)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by jenshweber** [comment]
I just downloaded FeatureIDE and found that it is still not possible to add a feature above. Is this function going to be repaired soon? It appears like a major problem with the current release

**Comment by tthuem** [comment]
To clarify: This issue is about selecting several features and creating a feature above. Did you also experience problems when selecting only one feature and creating a feature above?

**Comment by jenshweber** [comment]
I experienced the problem only when selecting several features and trying to create a feature above. To be precise, I worked through the "Hello World" tutorial, which includes a step where you have to select two features and create a feature above. That step is currently not possible.

**Comment by tthuem** [comment]
Thanks for clarification. This is indeed anoying and it will be fixed within one of the next hot fixes.

**Comment by Subaro** [comment]
@Kogoro Can you test on branch issue-427 that everything is working as intended? Also, test if the issue #523 is appearing again (should not). After that, you can merge the branch.

**Comment by meinicke** [comment]
Reverting the operation does not work correctly:
Add a feature above - Ctrl+Z 

Then the new feature is not correctly removed.

![revertaddabove](https://cloud.githubusercontent.com/assets/1482595/26124746/6fda9fd2-3a34-11e7-8e28-1ee57a52e769.PNG)

**Comment by Subaro** [comment]
@meinicke I don´t get the problem but I changed a little bit. Could you try again and see if it happens again?

**Comment by Kogoro** [comment]
For me, the reverse operation is correctly removed now.

**Comment by meinicke** [comment]
The example from above works for me.

However, sometimes the order of features is no longer correct after reverting, see example:
![capture1](https://cloud.githubusercontent.com/assets/1482595/26322516/3bb074e2-3ee0-11e7-991c-19e157676bf2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1482595/26322519/3e369b92-3ee0-11e7-93da-ebb2e1352b2f.PNG)
![capture3](https://cloud.githubusercontent.com/assets/1482595/26322521/4017f8e8-3ee0-11e7-906f-3d38afaf79c5.PNG)

**Comment by Subaro** [comment]
Is now working correctly. The features are now added in the right order after reversing the action.
