### ISSUE TITLE
Non-terminating jobs when importing all FeatureIDE examples

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#489]
Created a new workspace, imported all examples (except those with Android and DeltaJ) of the release branch and then the progress is unchanged for minutes:

![freeze](https://cloud.githubusercontent.com/assets/5330357/24599138/1f5b6598-184f-11e7-8a9d-09d67e37bbd1.PNG)

Eclipse does still react, but I cannot perform any further changes as they will wait for the jobs to finish. Canceling all jobs has no effect.

![freeze2](https://cloud.githubusercontent.com/assets/5330357/24599204/5ae7aa36-184f-11e7-8b9c-2cff1d2d17ee.PNG)

Seems to be caused by the job for detecting library folders. I think I have seen this also for a single FeatureHouse project already.

**Comment by tthuem** [comment]
Terminating and restarting Eclipse helps at least that all jobs are then finished within several minutes (mainly due to BerkeleyDB). Not sure how far this workaround helps, as projects may not be properly added in the end.

**Comment by tthuem** [comment]
Job freeze did not occur when omitting all FeatureHouse examples from import.

**Comment by tthuem** [comment]
Could be due to a bug in a PHP plug-in that I installed:

```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-4.5.2/../workspace-4.5.2-runtime-release-test -dev file:C:/Users/tthuem/Tools/workspace-4.5.2/.metadata/.plugins/org.eclipse.pde.core/FeatureIDE Release Test/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

org.eclipse.core.jobs
Error
Mon Apr 03 09:47:02 CEST 2017
An internal error occurred during: "Detecting library folders".

java.lang.IllegalStateException: Preference node "org.eclipse.wst.validation" has been removed.
	at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:200)
	at org.eclipse.core.internal.resources.ProjectPreferences.internalGet(ProjectPreferences.java:429)
	at org.eclipse.core.internal.preferences.EclipsePreferences.get(EclipsePreferences.java:484)
	at org.eclipse.wst.validation.internal.PreferencesWrapper$PreferencesWrapperPersistent.get(PreferencesWrapper.java:114)
	at org.eclipse.php.internal.core.libfolders.AutoDetectLibraryFolderJob.hasDisabledPreference(AutoDetectLibraryFolderJob.java:97)
	at org.eclipse.php.internal.core.libfolders.AutoDetectLibraryFolderJob.runInWorkspace(AutoDetectLibraryFolderJob.java:65)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by tthuem** [comment]
Seems to be a feature interaction between FeatureHouse and PHP-related plug-ins or simply a problem with PHP plug-ins itself. Won't fix that.
