### ISSUE TITLE
Null pointer when importing FeatureC++ examples

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#490]
Imported all examples except FeatureHouse, DeltaJ, and Android and got the following exception related to FeatureC++:

```
java.lang.NullPointerException
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.compose(FeatureCppWrapper.java:160)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.buildFSTModel(FeatureCppComposer.java:277)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.performFullBuild(FeatureCppComposer.java:147)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:172)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by Subaro** [comment]
The temporary configuration that was created for the FSTModell was named ".equation". That lead to a false temporary configuration that requires a configuration name which was not present. Is now fixed and i can import the FeatureC++ examples without NullPointer.

**Comment by Subaro** [comment]
After temporary configuration changes the following error will be thrown after importing FeatureC++ example.

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data E:\NeonWorkspace/../runtime-EclipseApplication -dev file:E:/NeonWorkspace/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -debug E:\NeonWorkspace\.metadata\.plugins\org.eclipse.pde.core\Eclipse Application/.options -os win32 -ws win32 -arch x86_64 -consoleLog

de.ovgu.featureide.fm.core
Error
Wed Apr 05 15:40:52 CEST 2017


java.lang.NullPointerException
	at de.ovgu.featureide.fm.core.io.EclipseFileSystem.write(EclipseFileSystem.java:62)
	at de.ovgu.featureide.fm.core.io.FileSystem.write(FileSystem.java:55)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.write(SimpleFileHandler.java:180)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.save(SimpleFileHandler.java:74)
	at de.ovgu.featureide.core.builder.ComposerExtensionClass.createTemporaryConfigrationsFile(ComposerExtensionClass.java:452)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.buildFSTModel(FeatureCppComposer.java:277)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.initialize(FeatureCppComposer.java:102)
	at de.ovgu.featureide.core.internal.FeatureProject.getComposer(FeatureProject.java:1184)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:398)
	at de.ovgu.featureide.core.internal.FeatureProject.access$8(FeatureProject.java:393)
	at de.ovgu.featureide.core.internal.FeatureProject$3.run(FeatureProject.java:350)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by Subaro** [comment]
Same goes for importing Feature House examples

**Comment by skrieter** [comment]
Should be fixed now.
Please try again, I don't get the error.

**Comment by Subaro** [comment]
Yes indeed. I don´t get the error anymore. Not for Feature++, FeatureHouse or any other project type.
