### ISSUE TITLE
Annoying pop up when framework projects contain compiler errors

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#493]
Added a new method to the interface of the HelloWorld example and a pop up comes whenever I safe the code to update all four plugins.

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\workspace-4.6.3-featureide/../workspace-4.6.1-runtime-FeatureIDEReleaseTest -dev file:C:/Users/tthuem/workspace-4.6.3-featureide/.metadata/.plugins/org.eclipse.pde.core/FeatureIDE Release Test/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

de.ovgu.featureide.core
Error
Mon Apr 03 13:16:20 CEST 2017
Errors running builder 'Extensible Feature Project Builder' on project 'HelloWorld-Framework'.

java.lang.NullPointerException
	at de.ovgu.featureide.core.framework.FrameworkModelBuilder.addRole(FrameworkModelBuilder.java:205)
	at de.ovgu.featureide.core.framework.FrameworkModelBuilder.buildModel(FrameworkModelBuilder.java:137)
	at de.ovgu.featureide.core.framework.FrameworkModelBuilder.buildModel(FrameworkModelBuilder.java:120)
	at de.ovgu.featureide.core.framework.FrameworkComposer.buildFSTModel(FrameworkComposer.java:137)
	at de.ovgu.featureide.core.framework.FrameworkComposer.performFullBuild(FrameworkComposer.java:169)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:172)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by tthuem** [comment]
In detail, the problem occurs when the info.xml refers to an interface which does not exist (anymore). There should be a problem marker instead.

**Comment by Kogoro** [comment]
Tried yesterday to catch the exception and prevent  the pop-up. Seems not that easy or I didn't found the right place.
Maybe we can disable auto-build when the interface is missing?

**Comment by tthuem** [comment]
Disable auto-build does not sound like an option. We rather need special treatment and problem markers for these cases.

**Comment by Kogoro** [comment]
As in my understanding, JDT builds changed Java projects automatically without any interaction from our side, or? Because I get all error markers for missing interface when renaming it like in JDT. So we must intercept in the JDT build process somehow, or am I wrong?

**Comment by tthuem** [comment]
The build process is started on the project that we have full control over. We can modify the class path or something similar to avoid the build if necessary. Why does the build itself does not report that problem?

**Comment by Kogoro** [comment]
![unbenannt2](https://cloud.githubusercontent.com/assets/8019776/24667859/193a0522-1965-11e7-8515-4054013ed413.PNG)
Looks actual like this for me. The error can be prevented with returning when an interface is tried to read but throws an IOException.
