### ISSUE TITLE
Null pointer when editing FeatureHouse code

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#502]
Edited HelloWorld-FH-JUnit example and in the process of renaming files and then classes therein, I got the following pop-up with errors. The weird thing is that I did not even had a color scheme, so there is nothing to annotate at all.

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-4.6.3-featureide/../workspace-4.6.3-runtime-FeatureIDE-Examples -dev file:C:/Users/tthuem/Tools/workspace-4.6.3-featureide/.metadata/.plugins/org.eclipse.pde.core/FeatureIDE Examples/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

org.eclipse.ui.workbench
Error
Wed Apr 05 13:25:47 CEST 2017
Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".

java.lang.NullPointerException
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.updateDirectives(ColorAnnotationModel.java:368)
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.updateAnnotations(ColorAnnotationModel.java:311)
	at de.ovgu.featureide.ui.editors.annotation.ColorAnnotationModel.attach(ColorAnnotationModel.java:205)
	at de.ovgu.featureide.ui.editors.annotation.EditorTracker.annotateEditor(EditorTracker.java:137)
	at de.ovgu.featureide.ui.editors.annotation.EditorTracker.access$1(EditorTracker.java:134)
	at de.ovgu.featureide.ui.editors.annotation.EditorTracker$2.partActivated(EditorTracker.java:86)
	at org.eclipse.ui.internal.PartService$6.run(PartService.java:149)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.PartService.partActivated(PartService.java:146)
	at org.eclipse.ui.internal.WorkbenchPage$15.run(WorkbenchPage.java:4986)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4983)
	at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4962)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:682)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:677)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1345)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.hidePart(PartServiceImpl.java:1284)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.closePart(StackRenderer.java:1296)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.access$2(StackRenderer.java:1278)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer$7.close(StackRenderer.java:1163)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1930)
	at org.eclipse.swt.custom.CTabFolder$1.handleEvent(CTabFolder.java:338)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tthuem** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/5330357/24703586/1527c0a6-1a04-11e7-9b65-2dec0298e866.PNG)

**Comment by tthuem** [comment]
Was able to reproduce the behavior. Take the example, rename a class only in the file, not the file name. Save the file, change focus to other editor/view and back to Java editor. Kawoom.

**Comment by Kogoro** [comment]
Should be fixed now. 
@tthuem Please test it again. On my machine, the error doesn't occur.

**Comment by tthuem** [comment]
Indeed, seems to be fixed. :)
