### ISSUE TITLE
NullPointer on saving configuration for BerkeleyDB

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#535]
#### Prerequisitives
* **Eclipse Version:**  `Neon.3`
* **FeatureIDE-Version:**  `develop`
* **Operating system:** `Win 10`
* **Java runtime used to run eclipse:** `1.7`

### Issue description
When changing the configuration of BerkeleyDB and saving the changes following errors occur:
```
java.lang.NullPointerException
	at de.ovgu.featureide.fm.core.configuration.Configuration.isValid(Configuration.java:278)
	at de.ovgu.featureide.core.internal.FeatureProject$7.execute(FeatureProject.java:1041)
	at de.ovgu.featureide.core.internal.FeatureProject$7.execute(FeatureProject.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
```
java.lang.NullPointerException
	at org.prop4j.solver.SatInstance.getVariable(SatInstance.java:197)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationPropagator$IsValidMethod.execute(ConfigurationPropagator.java:95)
	at de.ovgu.featureide.fm.core.configuration.ConfigurationPropagator$IsValidMethod.execute(ConfigurationPropagator.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:46)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:40)
	at de.ovgu.featureide.fm.core.configuration.Configuration.isValid(Configuration.java:278)
	at de.ovgu.featureide.core.internal.FeatureProject$7.execute(FeatureProject.java:1041)
	at de.ovgu.featureide.core.internal.FeatureProject$7.execute(FeatureProject.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by Subaro** [comment]
Same happened for TankWar-Antenna

**Comment by Subaro** [comment]
Seems to happen to every project. Some small projects got no problem.

**Comment by Subaro** [comment]
@skrieter Maybe it could happen because you changed that configuration files could be .xml or .config?
