### ISSUE TITLE
FeatureC++ : An internal error occurred during: "Load Model". 

### ISSUE THREAD

**Issue by kuoa** [FeatureIDE/FeatureIDE#559]
#### Prerequisitives
* **Eclipse Version:**  `4.6.3.M20170301-0400`
* **FeatureIDE-Version:**  `3.3.1`
* **Operating system:** `Debian GNU/Linux 9 (stretch) 64 bits`
* **Java runtime used to run eclipse:** `1.8.0_131`
* **FeatureIDE Composer:** `FeatureC++`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** `openjdk version "1.8.0_131"`

### Issue description
Creating a new project with the FeatureC++ composer raises the following errors.
I have tried 3 version of Eclipse (Neon, Mars, Luna) with 3 versions of FeatureIDE (3.3.1, 3.2.0, 2.7) and 2 versions of Eclipse CDT (9.1 and 8.8.1) and none of these combinations work.
From this point forward there is no way of using the plugin since this error shows frequently, so I use this fc++ binary https://sourceforge.net/p/featurecpp/wiki/Home/ and with a custom makefile everything works.

-------

Multiple problems have occured -> Building workspace -> Load model
An internal error occurred during: "Load Model".
java.lang.NullPointerException

java.lang.NullPointerException
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.openMessageBox(FeatureCppWrapper.java:237)
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.process(FeatureCppWrapper.java:214)
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.compose(FeatureCppWrapper.java:163)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.buildFSTModel(FeatureCppComposer.java:277)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.initialize(FeatureCppComposer.java:102)
	at de.ovgu.featureide.core.internal.FeatureProject.getComposer(FeatureProject.java:1166)
	at de.ovgu.featureide.core.internal.FeatureProject.loadModel(FeatureProject.java:399)
	at de.ovgu.featureide.core.internal.FeatureProject.access$8(FeatureProject.java:394)
	at de.ovgu.featureide.core.internal.FeatureProject$3.run(FeatureProject.java:351)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Session data:
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by Kogoro** [comment]
Closed in favor of #560 as they appear to be equal.
