### ISSUE TITLE
FeatureC++ : Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

### ISSUE THREAD

**Issue by kuoa** [FeatureIDE/FeatureIDE#560]
#### Prerequisitives
* **Eclipse Version:**  `4.6.3.M20170301-0400`
* **FeatureIDE-Version:**  `3.3.1`
* **Operating system:** `Debian GNU/Linux 9 (stretch) 64 bits`
* **Java runtime used to run eclipse:** `1.8.0_131`
* **FeatureIDE Composer:** `FeatureC++`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `openjdk version "1.8.0_131`

### Issue description
This issue is closely related to #559 .
When trying to "Set as current configuration" we get the following error and no folders are created in the Feature folder.

----

Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

java.lang.NullPointerException
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.openMessageBox(FeatureCppWrapper.java:237)
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.process(FeatureCppWrapper.java:214)
	at de.ovgu.featureide.featurecpp.wrapper.FeatureCppWrapper.compose(FeatureCppWrapper.java:163)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.buildFSTModel(FeatureCppComposer.java:277)
	at de.ovgu.featureide.featurecpp.FeatureCppComposer.performFullBuild(FeatureCppComposer.java:147)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:172)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:551)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at de.ovgu.featureide.core.internal.FeatureProject$5.execute(FeatureProject.java:636)
	at de.ovgu.featureide.core.internal.FeatureProject$5.execute(FeatureProject.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by Kogoro** [comment]
Folders are now working again and also no error occurs. So this issue will be closed.
@kuoa Thanks for the report and please feel free to open an issue when needed.

**Comment by kuoa** [comment]
Hello, sorry for my late response but I was working on something else and didn't had the chance to test the new version.

I installed the new version 3.3.2 and I still get issues in the same range as before (mostly An error has occurred. See error log for more details.
java.lang.NullPointerException). 

I can't create a new project in FeatureC++ nor modify the HelloWorld example.

The source of errors comes mostly from :

- Problems occurred when invoking code from plug-in: "org.eclipse.jface".
- An internal error occurred during: "Load Model".
- Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
- Errors running builder 'Extensible Feature Project Builder' on project 'Name of the project'.
- An internal error occurred during: "Update collaboration diagram".

I can provide error logs, screenshots and anything else that's necessary in order to help fixing this problem, either on github or email.
