### ISSUE TITLE
NullPointer when setting properties

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#590]
#### Prerequisitives
* **Git branch/Commit-ID:**  `develop`

### Issue description
Fast operations:
1. Import calm16_ceb feature model
2. Open feature model
3. Collapse all
4. Save and Close
5. NullPointer occurs 
```
java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.featuremodel.figures.ConstraintFigure.setConstraintProperties(ConstraintFigure.java:156)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.editparts.ConstraintEditPart.propertyChange(ConstraintEditPart.java:120)
	at de.ovgu.featureide.fm.ui.editors.elements.GraphicalConstraint.update(GraphicalConstraint.java:144)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$5.runInUIThread(FeatureDiagramEditor.java:927)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

```

**Comment by Kogoro** [comment]
Seems to be a concurrency issue between the feature model analyzer and initializing the tooltip, color, border. Both are Jobs in the FeatureDiagramEditor and the question is how we avoid such issues.

**Comment by Kogoro** [comment]
For both issues, could someone test the fix other than us?

**Comment by tthuem** [comment]
@Kogoro Are we still waiting for someone to test it? If so, I would like to ask @Subaro or @PaulWestphal .

**Comment by Kogoro** [comment]
I think this would be good.

**Comment by Subaro** [comment]
I tested on develop and no null pointer occurred

**Comment by Subaro** [comment]
The issues doe's not appeared on the release branch. The fixing commit was only performed on the develop
