### ISSUE TITLE
NullPointer on saving model when analysis still runs

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#591]
#### Prerequisitives
* **Git branch/Commit-ID:**  `develop`

### Issue description
Fast operations:
1. Open model.xml from cq7750 example
2. Collapse all
3. Save and close (The analyzer works now)
4. Seems that FeatureIDE tries to check for a stop the analyzer

```
de.ovgu.featureide.fm.core.job.monitor.IMonitor$MethodCancelException
	at de.ovgu.featureide.fm.core.job.monitor.ProgressMonitor.checkCancel(ProgressMonitor.java:71)
	at org.prop4j.analyses.FeatureModelAnalysis.checkConstraintDeadAndFalseOptional(FeatureModelAnalysis.java:307)
	at org.prop4j.analyses.FeatureModelAnalysis.updateConstraints(FeatureModelAnalysis.java:255)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:205)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:46)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.analyzeFeatureModel(FeatureModelAnalyzer.java:624)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:894)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
java.lang.NullPointerException
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:195)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:46)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.analyzeFeatureModel(FeatureModelAnalyzer.java:624)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:894)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
```
!ENTRY org.eclipse.ui 4 4 2017-09-22 00:33:38.559
!MESSAGE An internal error has occurred.
!STACK 0
java.lang.NullPointerException
de.ovgu.featureide.fm.core.job.monitor.IMonitor$MethodCancelException
	at de.ovgu.featureide.fm.core.job.monitor.ProgressMonitor.checkCancel(ProgressMonitor.java:71)
	at org.prop4j.analyses.FeatureModelAnalysis.checkConstraintDeadAndFalseOptional(FeatureModelAnalysis.java:307)
	at org.prop4j.analyses.FeatureModelAnalysis.updateConstraints(FeatureModelAnalysis.java:255)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:205)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:46)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.analyzeFeatureModel(FeatureModelAnalyzer.java:624)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:894)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at de.ovgu.featureide.fm.core.base.FeatureUtils.setRelevantConstraints(FeatureUtils.java:1304)
	at org.prop4j.analyses.FeatureModelAnalysis.updateFeatures(FeatureModelAnalysis.java:216)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:201)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:46)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.analyzeFeatureModel(FeatureModelAnalyzer.java:624)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:894)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:41)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:47)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by DawidSA2017** [comment]
By changing the feature name or description on the source tab, then changing to "Feature Diagram" tab the above error (ConcurrentModificationException) is thrown. This only happens on very sizeable feature models.

**Comment by Kogoro** [comment]
On develop there are still errors:
Without popup:
```
de.ovgu.featureide.fm.core.job.monitor.IMonitor$MethodCancelException
	at de.ovgu.featureide.fm.core.job.monitor.ProgressMonitor.checkCancel(ProgressMonitor.java:70)
	at org.prop4j.analyses.FeatureModelAnalysis.checkConstraintDeadAndFalseOptional(FeatureModelAnalysis.java:304)
	at org.prop4j.analyses.FeatureModelAnalysis.updateConstraints(FeatureModelAnalysis.java:252)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:202)
	at org.prop4j.analyses.FeatureModelAnalysis.execute(FeatureModelAnalysis.java:1)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:45)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.analyzeFeatureModel(FeatureModelAnalyzer.java:578)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:895)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:40)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:121)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:885)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:40)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:121)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
With Popup:
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:885)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$4$1.execute(FeatureDiagramEditor.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:40)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:121)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by tthuem** [comment]
Who can fix this?

**Comment by tthuem** [comment]
Kind of fixed, but job should be cancelled instead.

**Comment by skrieter** [comment]
Just as a side note: MethodCancelException is now properly catched by LongRunningWrapper (see 3969dea01f154fdf0554a5537a8fa96742850c94)
