### ISSUE TITLE
Add PROFilE examples

### ISSUE THREAD

**Issue by TimoGuenther** [FeatureIDE/FeatureIDE#606]
I am in the process of adding the configurations from PROFilE as examples to FeatureIDE. As instructed by the readme, I added the example projects to `featureide_examples` and ran `build.xml` as an Ant script. However, the script does nothing for me, not even console output.

The example project files are on the branch `profile_examples` as of https://github.com/FeatureIDE/FeatureIDE/commit/2c7e8a695f2030aa2b7398010c8ffd9f5318ec2d.

**Comment by TimoGuenther** [comment]
Turns out the readme is a liar and you are supposed to run `UpdateIndexFiles.laucnh`. Unfortunately, I get the following output when running that:

> Examining Files...
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/CoreException : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at de.ovgu.featureide.examples.utils.CreateMetaInformation$ProjectWalker.visitFile(CreateMetaInformation.java:152)
    at de.ovgu.featureide.examples.utils.CreateMetaInformation$ProjectWalker.visitFile(CreateMetaInformation.java:1)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
    at java.nio.file.Files.walkFileTree(Files.java:2602)
    at java.nio.file.Files.walkFileTree(Files.java:2635)
    at de.ovgu.featureide.examples.utils.CreateMetaInformation.main(CreateMetaInformation.java:207)

**Comment by TimoGuenther** [comment]
Thanks to @Kogoro for running the script (https://github.com/FeatureIDE/FeatureIDE/commit/81b34032829523d84e9c3b80fb31d70f1dd2feec).

As requested in #616, I transformed the feature models to the FeatureIDE format (https://github.com/FeatureIDE/FeatureIDE/commit/7b025b5b8f4cdc46d872af7a652ab3a799f6b486). However, an error marker due to an unknown XML tag prevents the feature diagram from being opened. The error marker is caused by this line:

https://github.com/FeatureIDE/FeatureIDE/blob/7b025b5b8f4cdc46d872af7a652ab3a799f6b486/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/sxfm/SXFMFormat.java#L326

Commenting out this line makes it possible to open the feature diagram without errors. Since the feature diagram seems to be intact, this suggests that the format transformation was done correctly and FeatureIDE just fails to load the model.

Should this not be the case, I made sure the original feature model data is still available (https://github.com/FeatureIDE/FeatureIDE/commit/f6e06652e178d5c66a95290d44fe3974d593dbcc).

I also added the descriptions from the readme (https://github.com/FeatureIDE/FeatureIDE/commit/a1fb27698e6e1aea5c674388e226229ed2a8e3e9).

**Comment by tthuem** [comment]
@skrieter Why is the wrong format used in this case? See above.

**Comment by skrieter** [comment]
This error doesn't occur for me.
Neither on the `profile_examples` nor the `develop` branch.
Both formats can be opened just fine in the feature model editor.

**Comment by skrieter** [comment]
By the way, is there a problem with the build.xml script?
Is works on my machine. :)

**Comment by TimoGuenther** [comment]
I could not get the build script to function on Linux Mint, where it throws an exception every time. It works on Windows 7.

**Comment by TimoGuenther** [comment]
Odd, both @Kogoro and me used to get said `UnsupportedModelException`, but I don't receive it either anymore.

**Comment by tthuem** [comment]
If everything works now, go ahead and merge it into develop.

**Comment by TimoGuenther** [comment]
Merged as of https://github.com/FeatureIDE/FeatureIDE/commit/c10150a62277f37fdf4a14151ebe20b365e70958.
