### ISSUE TITLE
Sporadic exception for explanations

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#619]
The following exception occurred when executing the following GUI test: https://github.com/FeatureIDE/FeatureIDE/blob/develop/gui-tests/de.ovgu.featureide.fm.gui-test/testCases/views/outline/EditFeatureModelInOutline.test

However, it only happens sporadically in about 1 of 10 runs, but I've seen this twice already on different test cases. It is only a minor issue, as I could not see any misbehavior except this silent exception in the error log (no popup).

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_141
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.rcp.product -eclipse.keyring C:\Users\tthuem\Tools\workspace-4.6.3-rcp\.metadata\.plugins\org.eclipse.pde.core\org.eclipse.epp.package.rcp.product/secure_storage
Command-line arguments:  -product org.eclipse.epp.package.rcp.product -data C:\Users\tthuem\Tools\workspace-4.6.3-rcp/../aut-org.eclipse.epp.package.rcp.product -dev file:C:/Users/tthuem/Tools/workspace-4.6.3-rcp/.metadata/.plugins/org.eclipse.pde.core/org.eclipse.epp.package.rcp.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -eclipse.keyring C:\Users\tthuem\Tools\workspace-4.6.3-rcp\.metadata\.plugins\org.eclipse.pde.core\org.eclipse.epp.package.rcp.product/secure_storage

org.eclipse.ui
Error
Fri Oct 06 00:22:33 CEST 2017
An internal error has occurred.

java.lang.IndexOutOfBoundsException: Index: 7, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at de.ovgu.featureide.fm.core.editing.FeatureModelToNodeTraceModel.getTrace(FeatureModelToNodeTraceModel.java:416)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.AbstractFeatureModelExplanationCreator.getReason(AbstractFeatureModelExplanationCreator.java:237)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.AbstractFeatureModelExplanationCreator.getExplanation(AbstractFeatureModelExplanationCreator.java:194)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.AbstractFeatureModelExplanationCreator.getExplanation(AbstractFeatureModelExplanationCreator.java:212)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.ltms.LtmsFalseOptionalFeatureExplanationCreator.getExplanation(LtmsFalseOptionalFeatureExplanationCreator.java:71)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.ltms.LtmsFalseOptionalFeatureExplanationCreator.getExplanation(LtmsFalseOptionalFeatureExplanationCreator.java:66)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.ltms.LtmsFalseOptionalFeatureExplanationCreator.getExplanation(LtmsFalseOptionalFeatureExplanationCreator.java:1)
	at de.ovgu.featureide.fm.core.explanations.impl.composite.CompositeExplanationCreator.getExplanation(CompositeExplanationCreator.java:81)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.composite.CompositeFalseOptionalFeatureExplanationCreator.getExplanation(CompositeFalseOptionalFeatureExplanationCreator.java:53)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.addFalseOptionalFeatureExplanation(FeatureModelAnalyzer.java:986)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getFalseOptionalFeatureExplanation(FeatureModelAnalyzer.java:966)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getExplanation(FeatureModelAnalyzer.java:866)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getExplanation(FeatureModelAnalyzer.java:847)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor.setActiveExplanation(FeatureDiagramEditor.java:443)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$5.runInUIThread(FeatureDiagramEditor.java:962)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run_aroundBody0(RunnableLock.java:35)
	at org.eclipse.swt.widgets.RunnableLock$AjcClosure1.run(RunnableLock.java:1)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$10$90b1ba39proceed(DisplayAspect.aj:345)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$10$90b1ba39(DisplayAspect.aj:367)
	at org.eclipse.swt.widgets.RunnableLock.run_aroundBody2(RunnableLock.java:35)
	at org.eclipse.swt.widgets.RunnableLock$AjcClosure3.run(RunnableLock.java:1)
	at org.eclipse.rcptt.sherlock.aspects.swt.DisplayAspect.ajc$around$org_eclipse_rcptt_sherlock_aspects_swt_DisplayAspect$2$90b1ba39proceed(DisplayAspect.aj:41)
	at org.eclipse.rcptt.sherlock.aspects.swt.DisplayAspect.ajc$around$org_eclipse_rcptt_sherlock_aspects_swt_DisplayAspect$2$90b1ba39(DisplayAspect.aj:63)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by TimoGuenther** [comment]
Does this also happen on the branch `explanations`?

**Comment by tthuem** [comment]
I cannot test this as your explanations branch does still contain the cycle dependency already fixed in develop branch. Can we merge develop into explanations?

**Comment by TimoGuenther** [comment]
Okay, `develop` merged into `explanations` as of https://github.com/FeatureIDE/FeatureIDE/commit/314567ce8b703a72398667a12b29bb79c0c02987.

**Comment by tthuem** [comment]
Does still occur.

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_141
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.rcp.product -eclipse.keyring C:\Users\tthuem\Tools\workspace-4.6.3-rcp\.metadata\.plugins\org.eclipse.pde.core\org.eclipse.epp.package.rcp.product/secure_storage
Command-line arguments:  -product org.eclipse.epp.package.rcp.product -data C:\Users\tthuem\Tools\workspace-4.6.3-rcp/../aut-org.eclipse.epp.package.rcp.product -dev file:C:/Users/tthuem/Tools/workspace-4.6.3-rcp/.metadata/.plugins/org.eclipse.pde.core/org.eclipse.epp.package.rcp.product/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -eclipse.keyring C:\Users\tthuem\Tools\workspace-4.6.3-rcp\.metadata\.plugins\org.eclipse.pde.core\org.eclipse.epp.package.rcp.product/secure_storage

org.eclipse.ui
Error
Fri Oct 06 17:37:37 CEST 2017
An internal error has occurred.

java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at de.ovgu.featureide.fm.core.editing.FeatureModelToNodeTraceModel.getTrace(FeatureModelToNodeTraceModel.java:416)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.AbstractFeatureModelExplanationCreator.getReason(AbstractFeatureModelExplanationCreator.java:145)
	at de.ovgu.featureide.fm.core.explanations.impl.AbstractExplanationCreator.getExplanation(AbstractExplanationCreator.java:94)
	at de.ovgu.featureide.fm.core.explanations.impl.AbstractExplanationCreator.getExplanation(AbstractExplanationCreator.java:112)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.ltms.LtmsFalseOptionalFeatureExplanationCreator.getExplanation(LtmsFalseOptionalFeatureExplanationCreator.java:51)
	at de.ovgu.featureide.fm.core.explanations.fm.impl.ltms.LtmsFalseOptionalFeatureExplanationCreator.getExplanation(LtmsFalseOptionalFeatureExplanationCreator.java:1)
	at de.ovgu.featureide.fm.core.explanations.impl.composite.CompositeExplanationCreator.getExplanation(CompositeExplanationCreator.java:84)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.addFalseOptionalFeatureExplanation(FeatureModelAnalyzer.java:988)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getFalseOptionalFeatureExplanation(FeatureModelAnalyzer.java:968)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getExplanation(FeatureModelAnalyzer.java:869)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.getExplanation(FeatureModelAnalyzer.java:850)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor.setActiveExplanation(FeatureDiagramEditor.java:445)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$5.runInUIThread(FeatureDiagramEditor.java:941)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run_aroundBody0(RunnableLock.java:35)
	at org.eclipse.swt.widgets.RunnableLock$AjcClosure1.run(RunnableLock.java:1)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$10$90b1ba39proceed(DisplayAspect.aj:345)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$10$90b1ba39(DisplayAspect.aj:367)
	at org.eclipse.swt.widgets.RunnableLock.run_aroundBody2(RunnableLock.java:35)
	at org.eclipse.swt.widgets.RunnableLock$AjcClosure3.run(RunnableLock.java:1)
	at org.eclipse.rcptt.sherlock.aspects.swt.DisplayAspect.ajc$around$org_eclipse_rcptt_sherlock_aspects_swt_DisplayAspect$2$90b1ba39proceed(DisplayAspect.aj:41)
	at org.eclipse.rcptt.sherlock.aspects.swt.DisplayAspect.ajc$around$org_eclipse_rcptt_sherlock_aspects_swt_DisplayAspect$2$90b1ba39(DisplayAspect.aj:63)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by tthuem** [comment]
Haven't seen this for a while. Hopefully it is no problem anymore.
