### ISSUE TITLE
Improve efficiency of automated collapsing to adjust to editor size

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#621]
Current implementation gives runs out of memory for Automotive02_V1. A greedy algorithm should scale better.

```
eclipse.buildId=4.7.0.I20170612-0950
java.version=1.8.0_141
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-4.7.0/../runtime-EclipseApplication -dev file:C:/Users/tthuem/Tools/workspace-4.7.0/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86 -consoleLog

org.eclipse.ui
Error
Sat Oct 07 18:58:05 CEST 2017
Unhandled event loop exception

java.lang.OutOfMemoryError: Java heap space
	at java.util.LinkedList.addAll(Unknown Source)
	at java.util.LinkedList.addAll(Unknown Source)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AdjustModelToEditorSizeOperation.powerSet(AdjustModelToEditorSizeOperation.java:197)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AdjustModelToEditorSizeOperation.calculateNextLevel(AdjustModelToEditorSizeOperation.java:143)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AdjustModelToEditorSizeOperation.calculateVisibleLayer(AdjustModelToEditorSizeOperation.java:125)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AdjustModelToEditorSizeOperation.operation(AdjustModelToEditorSizeOperation.java:68)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.redo(AbstractFeatureModelOperation.java:87)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.redo(AbstractFeatureModelOperation.java:75)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.execute(AbstractFeatureModelOperation.java:69)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.AdjustModelToEditorSizeAction.run(AdjustModelToEditorSizeAction.java:64)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$174/18683224.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.ui.internal.Workbench$$Lambda$14/17507993.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
```

**Comment by skrieter** [comment]
Implemented in [SP_MD_SoSe2018](https://github.com/FeatureIDE/FeatureIDE/tree/SP_MD_SoSe2018).
