### ISSUE TITLE
Cannot open Feature Diagramm when renaming a feature in the source tab.

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#645]
#### Prerequisitives
* **Eclipse Version:**  `Oxygen`
* **FeatureIDE-Version:**  `develop as of `22abb50a65f4efa6f2517a84fd080f9933e2d2df` `
* **Operating system:** `Win 10`
* **Java runtime used to run eclipse:** `1.7`

### Issue description
Open model -> Source Tab -> Change name of any feature -> (save/do not save) -> Feature Diagram tab:

```
de.ovgu.featureide.fm.core.io.UnsupportedModelException: Feature "ColorGdreenn" does not exists
	at de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat.throwError(XmlFeatureModelFormat.java:583)
	at de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat.parseConstraints2(XmlFeatureModelFormat.java:438)
	at de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat.parseConstraints2(XmlFeatureModelFormat.java:427)
	at de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat.parseConstraints(XmlFeatureModelFormat.java:393)
	at de.ovgu.featureide.fm.core.io.xml.XmlFeatureModelFormat.readDocument(XmlFeatureModelFormat.java:101)
	at de.ovgu.featureide.fm.core.io.xml.AXMLFormat.read(AXMLFormat.java:150)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.checkModel(FeatureModelEditor.java:155)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelTextEditorPage.allowPageChange(FeatureModelTextEditorPage.java:138)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.pageChange(FeatureModelEditor.java:462)
	at org.eclipse.ui.part.MultiPageEditorPart.lambda$1(MultiPageEditorPart.java:285)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3187)
	at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1870)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:328)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

Changing mandatory or any other attributes still work without a problem.

**Comment by Subaro** [comment]
Seems that I oversaw the feature that I renamed in source tab in a constraint. It is behaving correctly.
