### ISSUE TITLE
Source files are not preprocessed when using XML configuration format

### ISSUE THREAD

**Issue by TimoGuenther** [FeatureIDE/FeatureIDE#652]
When a `.config` file is the active configuration, files are preprocessed normally. However, when a `.xml` file is the active configuration, files are not preprocessed. An exemplary symptom of this is that no markers are created if there are issues with the preprocessor annotations such as misspelled feature names.

This behavior depends on the preprocessor used. The problem occurs with Antenna but not with CPP, for example.

**Comment by Subaro** [comment]
I think the trigger for not preprocessing the files is the following error that is thrown when a `.xml` file is the active configuration:

I used the Antenna Hello World Example with the BeautifulWorld.xml configuration.


```
antenna.preprocessor.v3.PPException: Error evaluating symbols "<?xml version="1.0" encoding="UTF-8" standalone="no"?>,	<configuration>,		<feature automatic="undefined" manual="undefined" name="HelloWorld"/>,		<feature automatic="undefined" manual="undefined" name="Feature"/>,		<feature automatic="undefined" manual="undefined" name="Wonderful"/>,		<feature automatic="undefined" manual="undefined" name="Beautiful"/>,		<feature automatic="undefined" manual="undefined" name="World"/>,	</configuration>"
	at antenna.preprocessor.v3.Preprocessor.addDefines(Preprocessor.java:165)
	at de.ovgu.featureide.antenna.AntennaPreprocessor.performFullBuild(AntennaPreprocessor.java:144)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:185)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: NoViableAltException(16@[206:1: defines : ( ( EOL | EOF ) | define ( COMMA define )* ( EOL )? );])
	at antenna.preprocessor.v3.parser.APPParser.defines(APPParser.java:2219)
	at antenna.preprocessor.v3.parser.Defines.addDefines(Defines.java:101)
	at antenna.preprocessor.v3.Preprocessor.addDefines(Preprocessor.java:163)
	... 14 more

```

Like @TimoGuenther said it is only thrown for Antenna.

**Comment by Subaro** [comment]
The PPComposerExtensionClass has currently no implementation for reading `.xml` configurations. It got the `.xml` source as a list instead of the selected features.

**Comment by tthuem** [comment]
We should discuss it in our meeting.
