### ISSUE TITLE
Print to PDF does not work anymore

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#653]
Besides a NullPointer, it seems that the legend is not always moved together with the rest of the diagram to the top left corner.

```
eclipse.buildId=4.7.0.I20170612-0950
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-4.7.0/../runtime-EclipseApplication -dev file:C:/Users/tthuem/Tools/workspace-4.7.0/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86 -consoleLog

org.eclipse.ui
Error
Wed Oct 25 09:50:54 CEST 2017
Unhandled event loop exception

org.eclipse.e4.core.di.InjectionException: org.eclipse.core.commands.ExecutionException: While executing the action, an exception occurred
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: org.eclipse.core.commands.ExecutionException: While executing the action, an exception occurred
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:123)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 37 more
Caused by: java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.featuremodel.figures.RelationDecoration.calculateAngle(RelationDecoration.java:153)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.figures.RelationDecoration.drawShape(RelationDecoration.java:119)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.figures.RelationDecoration.outlineShape(RelationDecoration.java:92)
	at org.eclipse.draw2d.Shape.paintOutline(Shape.java:175)
	at org.eclipse.draw2d.Shape.paintFigure(Shape.java:147)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1118)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1170)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1205)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1120)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1170)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1200)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1120)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1170)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1209)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1120)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1170)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1205)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1120)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1170)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1205)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1120)
	at org.eclipse.draw2d.PrintFigureOperation.printPages(PrintFigureOperation.java:137)
	at org.eclipse.draw2d.PrintOperation.run(PrintOperation.java:160)
	at org.eclipse.gef.ui.actions.PrintAction.run(PrintAction.java:74)
	at de.ovgu.featureide.fm.ui.editors.FMPrintAction.run(FMPrintAction.java:67)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
	... 43 more
```

**Comment by tthuem** [comment]
Why is this commit only in develop?

**Comment by Subaro** [comment]
@tthuem Because the print to pdf failed after merging the branch 'Enhancement_FeatureModelEditor_Toolbar'. At the moment this only affects the develop branch. Currently on release is no problem except 'legend is not always moved together with the rest of the diagram to the top left corner'. I created a separate issue #668 for the moving of the legend because that should also be fixed for release.
