### ISSUE TITLE
FM export does not work with extended fm as export option

### ISSUE THREAD

**Issue by Kogoro** [FeatureIDE/FeatureIDE#707]
#### Prerequisite
* **Git branch/Commit-ID:**  `develop`

### Issue description
Can't export a feature model when selecting the extended feature model format.
```
!ENTRY de.ovgu.featureide.fm.core 4 0 2018-02-15 12:41:13.643
!MESSAGE de.ovgu.featureide.fm.core.base.impl.Feature cannot be cast to de.ovgu.featureide.fm.attributes.base.impl.ExtendedFeature
!STACK 0
java.lang.ClassCastException: de.ovgu.featureide.fm.core.base.impl.Feature cannot be cast to de.ovgu.featureide.fm.attributes.base.impl.ExtendedFeature
	at de.ovgu.featureide.fm.attributes.format.XmlExtendedFeatureModelFormat.createFeatureAttributes(XmlExtendedFeatureModelFormat.java:228)
	at de.ovgu.featureide.fm.attributes.format.XmlExtendedFeatureModelFormat.createXmlDocRec(XmlExtendedFeatureModelFormat.java:283)
	at de.ovgu.featureide.fm.attributes.format.XmlExtendedFeatureModelFormat.writeDocument(XmlExtendedFeatureModelFormat.java:108)
	at de.ovgu.featureide.fm.core.io.xml.AXMLFormat.write(AXMLFormat.java:181)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.write(SimpleFileHandler.java:223)
	at de.ovgu.featureide.fm.core.io.manager.SimpleFileHandler.save(SimpleFileHandler.java:107)
	at de.ovgu.featureide.fm.ui.handlers.AExportHandler.save(AExportHandler.java:84)
	at de.ovgu.featureide.fm.ui.handlers.AExportHandler.singleAction(AExportHandler.java:63)
	at de.ovgu.featureide.fm.ui.handlers.base.AFileHandler.singleAction(AFileHandler.java:43)
	at de.ovgu.featureide.fm.ui.handlers.base.ASelectionHandler.execute(ASelectionHandler.java:53)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by Subaro** [comment]
I fixed the issue on our fork but can make a sperate fix for FeatureIDE.

**Comment by tthuem** [comment]
@Subaro Would be great to have that fixed in release3.5 and develop.
