### ISSUE TITLE
Add color to feature not working

### ISSUE THREAD

**Issue by scas-mdd** [FeatureIDE/FeatureIDE#708]
#### Prerequisitives
* **Eclipse Version:**  `4.7.1 | 4.7.2 Add text here (needed for best issue handling)`
* **FeatureIDE-Version:**  `3.4.1 | 3.4.2 | 3.4.3`
* **Operating system:** `Win 10`
* **Java runtime used to run eclipse:** `Java 8 1.8.0_151`
* **FeatureIDE Composer:** `Add text here (optional, leave blank if not needed)`
* **Git branch/Commit-ID:**  `Add text here (optional, leave blank if not needed)`
* **Java compiler used to build the FeatureIDE plugin:** `Add text here (optional, leave blank if not needed)`

### Issue description
On existing project or simply on a new FeatureIDE project, I cannot assign any color to a feature. I select the Feature, I click the color desired and press OK and nothing happens. I tried on all 3 versions, 3.4.1, 3.4.2, 3.4.3, but also on 3.3.0 -- which works! 

Is it something on my side or can someone reproduce this?

**Comment by tthuem** [comment]
I cannot reproduce this problem. So I guess we probably need more data for reproduction.

Do you use a pre-configured Eclipse from the FeatureIDE website? If yes, which download exactly? If not, which Eclipse do you use? Does the issue occur with any of the FeatureIDE example projects? If so, with which features?

**Comment by scas-mdd** [comment]
Preconfigured FeatureIDE from website, v3.4.3
I create a new FeatureIDE project, I click on Base feature, feature Color, select one color and then nothing happens. 

If I try this via the EclipseCommitters, develop branch, commit: 1ec788a0
I get an error "setColor called on Default color scheme". 
Sometimes, in undeterministic behaviour, it works... Most of the times it does not. 

`!ENTRY org.eclipse.ui 4 0 2018-03-07 13:54:05.689
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.RuntimeException: setColor called on default color scheme
	at de.ovgu.featureide.fm.core.color.DefaultColorScheme.setColor(DefaultColorScheme.java:47)
	at de.ovgu.featureide.fm.core.color.FeatureColorManager.setColor(FeatureColorManager.java:88)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.SetFeatureColorOperation.operation(SetFeatureColorOperation.java:65)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.redo(AbstractFeatureModelOperation.java:88)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.colors.SetFeatureColorDialog.okPressed(SetFeatureColorDialog.java:339)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:466)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)`
