### ISSUE TITLE
Features and model.xml are not present when using Munge for Android 

### ISSUE THREAD

**Issue by alkalinan** [FeatureIDE/FeatureIDE#726]
#### Prerequisitives
* **Eclipse Version:**  `Oxygen.2 Release (4.7.2)`
* **FeatureIDE-Version:**  `3.4.3`
* **Operating system:** `MacOS 10.11.6`
* **Java runtime used to run eclipse:** `Java SE 8`
* **FeatureIDE Composer:** `Munge (Android)`
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description
When a new Android Munge is created, the model.xml and the feature folder are not created. Once manually created, the feature folder and the model.xml are not linked, which makes FeatureIDE useless because features declared in model.xml are not added to the project.

**Comment by alkalinan** [comment]
After more researches, I figure that the issue was only on the missing file "model.xml". Because Munge is an annotation method inside the code, there was no need for a "features" folder in the project.
However, configs folders is not created and it does not seem possible to add new config files to the project.

**Comment by Subaro** [comment]
I also investigated and the problem is a NullPointerException occurring on the creation of the project. The problem is not thrown from FeatureIDE.

```
java.lang.NullPointerException
	at com.android.ide.eclipse.adt.internal.actions.AddSupportJarAction.installAppCompatLibrary(AddSupportJarAction.java:327)
	at com.android.ide.eclipse.adt.internal.wizards.templates.NewProjectWizard$1.run(NewProjectWizard.java:280)
	at com.android.ide.eclipse.adt.internal.wizards.templates.NewProjectWizard.performFinish(NewProjectWizard.java:377)
	at com.android.ide.eclipse.adt.internal.wizards.templates.TemplateWizard$1.run(TemplateWizard.java:201)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```
