### ISSUE TITLE
Ant script for adding new examples does not work anymore

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#740]
```
Buildfile: C:\Users\tthuem\git\code-FeatureIDE\plugins\de.ovgu.featureide.examples\build.xml
createExampleInformation:
     [java] Examining Files...
     [java] Updating Index Files...
     [java] New index file for project CommandLineConfigurator was created. 
     [java] New index file for project GraphicalConfigurator was created. 
     [java] New index file for project PROFilE-E-Agribusiness was created. 
     [java] java.lang.NoClassDefFoundError: de/ovgu/featureide/fm/core/io/APersistentFormat
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:198)
     [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:834)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:228)
     [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:137)
     [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:110)
     [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [java] 	at java.lang.reflect.Method.invoke(Unknown Source)
     [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java] 	at org.apache.tools.ant.Task.perform(Task.java:348)
     [java] 	at org.apache.tools.ant.Target.execute(Target.java:435)
     [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
     [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java] 	at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
     [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [java] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:460)
     [java] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:142)
     [java] Caused by: java.lang.NoClassDefFoundError: de/ovgu/featureide/fm/core/io/APersistentFormat
     [java] 	at de.ovgu.featureide.examples.utils.CreateMetaInformation.main(CreateMetaInformation.java:217)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [java] 	at java.lang.reflect.Method.invoke(Unknown Source)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:221)
     [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:154)
     [java] 	... 20 more
     [java] Caused by: java.lang.ClassNotFoundException: de.ovgu.featureide.fm.core.io.APersistentFormat
     [java] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1384)
     [java] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1333)
     [java] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1094)
     [java] 	at java.lang.ClassLoader.loadClass(Unknown Source)
     [java] 	... 27 more
     [java] Java Result: -1
BUILD SUCCESSFUL
Total time: 14 seconds
```

**Comment by skrieter** [comment]
Updated readme in b19733c75dd63ecff40823a279afb74310a4b442
