### ISSUE TITLE
Concurrent Modification Exception in FeatureModel Edits

### ISSUE THREAD

**Issue by skrieter** [FeatureIDE/FeatureIDE#749]
#### Prerequisitives
* **Eclipse Version:**  `Neon`
* **FeatureIDE-Version:**  `3.5`
* **Operating system:** `Win 7`
* **Java runtime used to run eclipse:** `1.8`
* **Git branch/Commit-ID:**  `Release (bea8e5cb1e1aae0dbea5f3b26732a05c749d84ff)`

### Issue description
Error Message pops up sometimes when starting FeatureIDE with an open FeatureModelEditsView.

**Stacktrace**:
!ENTRY org.eclipse.core.jobs 4 2 2018-04-21 12:30:15.941
!MESSAGE An internal error occurred during: "Updating Feature Model Edits".
!STACK 0
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at de.ovgu.featureide.fm.core.configuration.TreeElement.removeChildren(TreeElement.java:59)
	at de.ovgu.featureide.fm.core.configuration.TreeElement.setChild(TreeElement.java:48)
	at de.ovgu.featureide.fm.ui.views.featuremodeleditview.ViewContentProvider.defaultContent(ViewContentProvider.java:181)
	at de.ovgu.featureide.fm.ui.views.FeatureModelEditView$5$1.run(FeatureModelEditView.java:316)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

One solution would be to synchronize the List or corresponding the methods in class TreeElement.
However, there might be a better solution, since TreeElement is also used by classes that do not require synchronization.

**Comment by Subaro** [comment]
@skrieter I made the list synchronized because I could not find the actuator for the ConcurrentModificationException. Therefore, could you test the fix? Thank you :)

@Kogoro Review?

**Comment by tthuem** [comment]
@Subaro Your answer on the code review is still missing: https://github.com/FeatureIDE/FeatureIDE/commit/c8d657885a1dd7abc386ffd65ebbfbf2bd595fac#commitcomment-29145422

**Comment by Subaro** [comment]
The code review was implemented with the 607c5dd threfore I did not wrote an answer. I did now because of your request.
