### ISSUE TITLE
Framework composer not intuitive or not working

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#779]
Framework composer has some serious issues or I am using the composer in the wrong way. 

1) Editing the feature model: As example adding the feature 'Test' does not create the folder 'Test' in the features folder and does not create the <ProjectName>-Test Plug-In. That only happens when the editor is restarted.

2) Editing the 'Test.java' does not build the binaries for the current Feature-PlugIn. At all I could not figure out how to build the binaries (bin folder). Therefore it is not possible to use the generated jars because they do not contain any .class files.

3) I do not understand when new .jar files are generated. The only way i found is to change the configuration and do a save operation. Then new .jar files are generated. But changing sources code does nothing.

**Comment by PaulWestphal** [comment]
When opening a project that uses the framework composer, it gets stuck in a build loop:

`!ENTRY de.ovgu.featureide.core.framework 2 0 2019-01-13 15:10:44.552
!MESSAGE Wonderful not found
!STACK 0
java.lang.Exception
	at de.ovgu.featureide.fm.core.AbstractCorePlugin.logWarning(AbstractCorePlugin.java:82)
	at de.ovgu.featureide.core.framework.FrameworkModelBuilder.addRole(FrameworkModelBuilder.java:186)
	at de.ovgu.featureide.core.framework.FrameworkModelBuilder.buildModel(FrameworkModelBuilder.java:134)
	at de.ovgu.featureide.core.framework.FrameworkModelBuilder.buildModel(FrameworkModelBuilder.java:117)
	at de.ovgu.featureide.core.framework.FrameworkComposer.buildFSTModel(FrameworkComposer.java:134)
	at de.ovgu.featureide.core.framework.FrameworkComposer.performFullBuild(FrameworkComposer.java:166)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:274)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:457)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:571)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:545)
	at org.eclipse.core.internal.resources.Project.build(Project.java:113)
	at de.ovgu.featureide.core.framework.FrameworkComposer.performFullBuild(FrameworkComposer.java:170)
	at de.ovgu.featureide.core.builder.ExtensibleFeatureProjectBuilder.build(ExtensibleFeatureProjectBuilder.java:180)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)`

(...)

Until this error eventually pops up:

![internalerror](https://user-images.githubusercontent.com/32126695/51086922-b568ac00-174c-11e9-829b-f635939cd6c7.PNG)


That might be the cause of these problems.

**Comment by PaulWestphal** [comment]
>1. Editing the feature model: As example adding the feature 'Test' does not create the folder 'Test' in the features folder and does not create the -Test Plug-In. That only happens when the editor is restarted.

Creating a new feature also creates a new folder in the "features" folder with that feature's name. It is empty, I'm not sure if there are supposed to be auto-generated files in there.

>2. Editing the 'Test.java' does not build the binaries for the current Feature-PlugIn. At all I could not figure out how to build the binaries (bin folder). Therefore it is not possible to use the generated jars because they do not contain any .class files.

Editing a java file in the "features" folder now builds corresponding .class files in the "bin" folder.

>3. I do not understand when new .jar files are generated. The only way i found is to change the configuration and do a save operation. Then new .jar files are generated. But changing sources code does nothing.

Existing .jar files are re-built when there's a change in a .java file. And new .jar files are built when there's a configuration that uses those .java files.

It seems that these issues were all caused by the build loop. Are there supposed to be auto-generated files in newly created folders the "features" folder? If not, everything seems to be working as intended.

**Comment by tthuem** [comment]
I don't think that we've had any auto-generated files.

@Subaro As you experienced all those problems, could you check the most recent version again?

**Comment by Subaro** [comment]
I tested the framework composer and everything seems to work fine.
