### ISSUE TITLE
Adding new example projects does not work

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#788]
For the next release, I need to add a new example project and step 3 in the readme.md does not work: 3. Run the launch file `UpdateIndexFiles.launch`

```
Examining Files...
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/CoreException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at de.ovgu.featureide.examples.utils.CreateMetaInformation$ProjectWalker.visitFile(CreateMetaInformation.java:152)
	at de.ovgu.featureide.examples.utils.CreateMetaInformation$ProjectWalker.visitFile(CreateMetaInformation.java:1)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at java.nio.file.Files.walkFileTree(Files.java:2635)
	at de.ovgu.featureide.examples.utils.CreateMetaInformation.main(CreateMetaInformation.java:207)
```

As this is urgent, how can help out? @skrieter @Kogoro @Subaro @PaulWestphal

**Comment by Kogoro** [comment]
Seems not like a problem with the implementation.

> java.lang.UnsupportedClassVersionError happens because of a higher JDK during compile time and lower JDK during runtime.

A solution could be:

> To fix the actual problem you should try to either run the Java code with a newer version of Java JRE or specify the target parameter to the Java compiler to instruct the compiler to create code compatible with earlier Java versions.

[Source](https://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi)

**Comment by tthuem** [comment]
Thanks, but this does not help. The code of the example plug-in is configured to be compiled with Java 7 and I'm using a JVM 10. Does the readme work for you?

**Comment by Kogoro** [comment]
The UpdateIndexFiles.launch run without problems for me.
My execution environment is `JavaSE-1.7 (jre1.8.0_151)` 
Classpath is JRE: `JavaSE-1.7`

**Comment by tthuem** [comment]
Seems that there was a problem with my Eclipse installation. I could not even edit any Java runtime configuration.

I started with a clean Eclipse installation and then it worked as expected.
