### ISSUE TITLE
Unhandled event loop exception when interacting with model editor on Ubuntu 17.10

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#796]
#### Prerequisitives
* **Eclipse Version:**  `4.7.3a`
* **FeatureIDE-Version:**  `3.5`
* **Operating system:** `Ubuntu 17.10`
* **Java runtime used to run eclipse:** `1.8.0_171`
* **FeatureIDE Composer:** ``
* **Git branch/Commit-ID:**  ``
* **Java compiler used to build the FeatureIDE plugin:** ``

### Issue description

In a completely new feature project and a completely new model.xml, I wanted to interact with the userinterface to add/insert new features to the model.xml, using the model editor view.

EDIT1: 
When clicking onto a feature, a error gets prompted (see below) and I'm not able to insert a new feature. Using the outline view of the model editor, I'm able to insert a feature, though it comes to unusual layout arrangement (top-down-order: feature below is placed in the left corner). Either way the model editor is not really usable.

Contents of the error log item:
Plugin: `org.eclipse.ui`
Message: `Unhandled event loop exception`
Exception Stack Trace: 
```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:180)
	at org.eclipse.draw2d.Cursors.<clinit>(Cursors.java:195)
	at org.eclipse.gef.tools.DragEditPartsTracker.<init>(DragEditPartsTracker.java:89)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getDragTracker(AbstractGraphicalEditPart.java:483)
	at org.eclipse.gef.tools.SelectionTool.handleButtonDown(SelectionTool.java:207)
	at org.eclipse.gef.tools.AbstractTool.mouseDown(AbstractTool.java:1091)
	at org.eclipse.gef.tools.SelectionTool.mouseDown(SelectionTool.java:512)
	at org.eclipse.gef.EditDomain.mouseDown(EditDomain.java:245)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMousePressed(DomainEventDispatcher.java:348)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseDown(LightweightSystem.java:523)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

Session data
```
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -data file:/home/cpwnd/eclipse-workspace/ -os linux -ws gtk -arch x86_64 
   -product org.eclipse.epp.package.committers.product
```

**Comment by cpwnd** [comment]
I updated my plugin and it happens also with most recent version of FeatureIDE 3.5.1

**Comment by cpwnd** [comment]
I checked out the zipped projects from featureide.github.io and the feature modelling version of 3.5.1 works just fine.

**Comment by cpwnd** [comment]
The first setup was FeatureIDE Linux 64 bit zip from http://featureide.cs.ovgu.de/downloads/eclipse4.7.3committers-featureide3.5.0-linux64.tar.gz.
Then after the first "crash" I fully updated the FeatureIDE plugin via the eclipse marketplace and it crashed again. Sorry I don't know if some plugins were/are missing.

No, in the second setup with the 3.5.1 zip from the downloads it won't appear again.

**Comment by tthuem** [comment]
As there haven't been any further reports, we are assuming this issue does not occur anymore. If it does occur again, we would be happy about a comment here.
