### ISSUE TITLE
Null pointer when renaming a feature in the feature diagram

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#816]
Renaming a feature in the feature model editor has lead to the following exception. In particular, it occurred during the tasks of the tutorial on a Mac. Thanks to Klaus Schmid for the report.

```
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_11
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.committers.product -keyring /Users/.../.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.committers.product -keyring /Users/schmid/.eclipse_keyring

de.ovgu.featureide.fm.core
Error
Tue Sep 11 10:35:32 CEST 2018
FAILED

java.lang.NullPointerException
                at de.ovgu.featureide.fm.core.configuration.Configuration.isValid(Configuration.java:275)
                at de.ovgu.featureide.core.internal.FeatureProject$7.execute(FeatureProject.java:1111)
                at de.ovgu.featureide.core.internal.FeatureProject$7.execute(FeatureProject.java:1)
                at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:44)
                at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
                at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:121)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by PaulWestphal** [comment]
I wasn't able to reproduce this.
