### ISSUE TITLE
Feature attributes are deleted when moving features in the feature model viewer

### ISSUE THREAD

**Issue by cpwnd** [FeatureIDE/FeatureIDE#829]
#### Prerequisitives
* **Eclipse Version:**  `oxygen 4.7.3.a`
* **FeatureIDE-Version:**  `3.5.2`
* **Operating system:** `windows 7 64`
* **Java runtime used to run eclipse:** `Build 1.8.0_161-b12`

### Issue description

1. Create new FeatureIDE project
2. Create new Feature model with two sub-features below the root feature(1) and for each feature create an attribute and save the model.
3. Now switch the order of the subfeatures (on their respective level) and refresh the feature attribute view.

**Expected**:
Order of features change. Attributes of the each sub features are unchanged.

**Observed**:
Order of features change. Attributes of the moved feature are beeing deleted.

This happenend when using the previous 3.5.1 version.

(1) This also happens when creating the sub-feature to a non root feature.

**Comment by cpwnd** [comment]
EDIT: When adding more than one attribute to features in step 2, it appears that only the first attribute of the moved feature is deleted.

**Comment by Subaro** [comment]
Actuator is the following exception
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at de.ovgu.featureide.fm.attributes.view.FeatureAttributeView.propertyChange(FeatureAttributeView.java:583)
	at de.ovgu.featureide.fm.core.base.event.DefaultEventManager.callListener(DefaultEventManager.java:53)
	at de.ovgu.featureide.fm.core.base.event.DefaultEventManager.fireEvent(DefaultEventManager.java:47)
	at de.ovgu.featureide.fm.core.base.impl.FeatureModel.fireEvent(FeatureModel.java:258)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.fireEvent(AbstractFeatureModelOperation.java:115)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.redo(AbstractFeatureModelOperation.java:88)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.redo(AbstractFeatureModelOperation.java:75)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.execute(AbstractFeatureModelOperation.java:69)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.commands.FeatureDragAndDropCommand.execute(FeatureDragAndDropCommand.java:123)
	at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:228)
	at org.eclipse.gef.tools.AbstractTool.executeCommand(AbstractTool.java:425)
	at org.eclipse.gef.tools.AbstractTool.executeCurrentCommand(AbstractTool.java:438)
	at org.eclipse.gef.tools.DragEditPartsTracker.performDrag(DragEditPartsTracker.java:538)
	at org.eclipse.gef.tools.DragEditPartsTracker.handleButtonUp(DragEditPartsTracker.java:393)
	at org.eclipse.gef.tools.AbstractTool.mouseUp(AbstractTool.java:1200)
	at org.eclipse.gef.tools.SelectionTool.mouseUp(SelectionTool.java:574)
	at org.eclipse.gef.EditDomain.mouseUp(EditDomain.java:301)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseReleased(DomainEventDispatcher.java:380)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseUp(LightweightSystem.java:548)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:221)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by Subaro** [comment]
Same exception on develop

**Comment by cpwnd** [comment]
great thanks
