### ISSUE TITLE
UI freezes and out of memory error when opening or working with large feature models

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#844]
#### Prerequisitives
* **Eclipse Version:**  4.7 + 4.8
* **FeatureIDE-Version:**  3.5.3 (edit: also confirmed for 3.4.3 except for the out of memory error)
* **Operating system:** Win 10

### Issue description
Import Automotive02_V4. Feature model opens rather quickly. Close feature model and remove .featureide/model.xml/model.xml.xml. Open feature model again. The UI freezes for minutes until the diagram is finally opened. Working with Eclipse while the feature model is opened is almost impossible, as the UI seems to freeze all the time.

Related to #695

**Comment by tthuem** [comment]
After a couple of minutes I got this exception without interacting with the IDE at all.

```
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_172
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product

org.eclipse.ui
Error
Thu Nov 29 14:56:01 CET 2018
Unhandled event loop exception

java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.draw2d.geometry.Rectangle.getCopy(Rectangle.java:361)
	at org.eclipse.draw2d.FreeformHelper.setFreeformBounds(FreeformHelper.java:88)
	at org.eclipse.draw2d.FreeformLayer.setFreeformBounds(FreeformLayer.java:90)
	at org.eclipse.draw2d.FreeformHelper.setFreeformBounds(FreeformHelper.java:94)
	at org.eclipse.draw2d.FreeformLayeredPane.setFreeformBounds(FreeformLayeredPane.java:106)
	at org.eclipse.draw2d.FreeformHelper.setFreeformBounds(FreeformHelper.java:94)
	at org.eclipse.draw2d.FreeformLayeredPane.setFreeformBounds(FreeformLayeredPane.java:106)
	at org.eclipse.draw2d.FreeformHelper.setFreeformBounds(FreeformHelper.java:94)
	at org.eclipse.draw2d.FreeformLayeredPane.setFreeformBounds(FreeformLayeredPane.java:106)
	at org.eclipse.draw2d.FreeformViewport.readjustScrollBars(FreeformViewport.java:72)
	at org.eclipse.draw2d.Viewport.validate(Viewport.java:381)
	at org.eclipse.draw2d.Figure.validate(Figure.java:1901)
	at org.eclipse.draw2d.DeferredUpdateManager.performValidation(DeferredUpdateManager.java:221)
	at org.eclipse.draw2d.DeferredUpdateManager.performUpdate(DeferredUpdateManager.java:193)
	at org.eclipse.draw2d.LightweightSystem.controlResized(LightweightSystem.java:125)
	at org.eclipse.draw2d.LightweightSystem$1.controlResized(LightweightSystem.java:105)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:236)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Control.sendResize(Control.java:3063)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1033)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1083)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3232)
	at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3228)
	at org.eclipse.swt.widgets.Control.setBounds(Control.java:3223)
	at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:204)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1359)
	at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1037)
	at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1083)
```

**Comment by tthuem** [comment]
![image](https://user-images.githubusercontent.com/5330357/49226689-9e156f80-f3e7-11e8-9cba-738d84789355.png)

**Comment by Subaro** [comment]
https://visualvm.github.io/
