### ISSUE TITLE
Changes in the feature diagram often lead to null pointer in the attributes view

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#856]
#### Prerequisitives
* **Eclipse Version:**  2018-09
* **FeatureIDE-Version:**  release 3.5 branch
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** JDK8
* **Git branch/Commit-ID:**  https://github.com/FeatureIDE/FeatureIDE/commit/2e06190ff2ea8c380d4f386048522e1619d43c3f
* **Java compiler used to build the FeatureIDE plugin:** JDK8

### Issue description
I double clicked a group type to change it and the attributes view resulted in a null pointer. Same when adding a new feature or deleting multiple features at the same time. However, it does not happen each time (potential race condition), but seen this problem numerous times on different changes. Could also depend on how the features are selected (i.e., I selected features by drawing a rectangle selection around them and then deleted them reproducing the problem).

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-2018-09/../workspace-2018-09-runtime -dev file:C:/Users/tthuem/Tools/workspace-2018-09/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

org.eclipse.ui
Error
Thu Jan 24 20:34:55 CET 2019
An internal error has occurred.

java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.featuremodel.editparts.FeatureEditPart.propertyChange(FeatureEditPart.java:206)
	at de.ovgu.featureide.fm.ui.editors.elements.GraphicalFeature.update(GraphicalFeature.java:219)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$3.runInUIThread(FeatureDiagramEditor.java:543)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-2018-09/../workspace-2018-09-runtime -dev file:C:/Users/tthuem/Tools/workspace-2018-09/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

org.eclipse.ui
Error
Thu Jan 24 20:57:45 CET 2019
An internal error has occurred.

java.lang.NullPointerException
	at de.ovgu.featureide.fm.attributes.view.FeatureAttributeContentProvider.getParent(FeatureAttributeContentProvider.java:108)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getParentElement(AbstractTreeViewer.java:1749)
	at org.eclipse.jface.viewers.TreeViewer.getParentElement(TreeViewer.java:566)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1678)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2515)
	at de.ovgu.featureide.fm.attributes.view.FeatureAttributeView$1.selectionChanged(FeatureAttributeView.java:190)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:247)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer$1.run(AbstractEditPartViewer.java:131)
	at org.eclipse.gef.SelectionManager.fireSelectionChanged(SelectionManager.java:156)
	at org.eclipse.gef.SelectionManager.deselect(SelectionManager.java:126)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.deselect(AbstractEditPartViewer.java:202)
	at org.eclipse.gef.editparts.AbstractEditPart.removeNotify(AbstractEditPart.java:942)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.removeNotify(AbstractGraphicalEditPart.java:823)
	at org.eclipse.gef.editparts.AbstractEditPart.removeChild(AbstractEditPart.java:880)
	at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:793)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:726)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:644)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$3.runInUIThread(FeatureDiagramEditor.java:580)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

The problem even does not disappear when closing the attributes view, which indicates that the listener is not removed from the feature diagram when the view is closed. I could not reproduce any of those problems when the attributes view was not open at startup and not opened either.

**Comment by Subaro** [comment]
I could fix the issue in the feature attribute view. The root feature was not considered when retrieving the parent. 

I could not reproduce the first issue.

**Comment by tthuem** [comment]
Thanks, could not reproduce the other issue either.
