### ISSUE TITLE
Null pointer while editing feature diagram

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#858]
#### Prerequisitives
* **Eclipse Version:**  2018-09
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201 (64-bit)
* **FeatureIDE Composer:** Extended Feature Modeling
* **Git branch/Commit-ID:**  release3.5 https://github.com/FeatureIDE/FeatureIDE/commit/cced953477aaa2dd012faf738fe82e531dfaae57
* **Java compiler used to build the FeatureIDE plugin:** Java 8 Update 201 (64-bit)

### Issue description
After adding and removing two features, assigning colors to features and removing those colors again, I got a null pointer exception in a pop-up. I did about ten changes before the exception was shown, but then it came after every edit, which is quite annoying. The edits itself still seemed to work fine.

I've reported this problem already earlier in #856. For reproduction, you may want to have a look at the setting posted in another issue #857. In particular the feature attributes view was opened, but I'm not sure this is relevant. The feature model being edited was an extended feature model.

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data C:\Users\tthuem\Tools\workspace-2018-09/../workspace-2018-09-runtime -dev file:C:/Users/tthuem/Tools/workspace-2018-09/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

org.eclipse.ui
Error
Fri Feb 01 10:42:10 CET 2019
An internal error has occurred.

java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.featuremodel.editparts.FeatureEditPart.propertyChange(FeatureEditPart.java:206)
	at de.ovgu.featureide.fm.ui.editors.elements.GraphicalFeature.update(GraphicalFeature.java:219)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor$3.runInUIThread(FeatureDiagramEditor.java:543)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

**Comment by tthuem** [comment]
@PaulWestphal @SundermannC @Subaro Who can have a look at this in the next days?

**Comment by PaulWestphal** [comment]
We managed to reproduce this bug accidentally once (it didn't seem like it had anything to do with the featureide colors), but couldn't figure out how to consistently reproduce it to work out a direct fix.
We cherry-picked a couple of fixes for related nullpointerexceptions in the same method (30e25baee20bee2f551db3b8b3deb676579661b7, a9c0d0a0b068c57713f48120a71928c0a487b4e4) from the develop branch that should have been in the release3.5 branch which may incidentally also fix this issue.
