### ISSUE TITLE
Issues with guidsl format in FeatureModelEditor

### ISSUE THREAD

**Issue by meinicke** [FeatureIDE/FeatureIDE#871]
#### Prerequisitives
* **Eclipse Version:**  `2018-12`
* **FeatureIDE-Version:**  `3.5`
* **Operating system:** `WIN10`
* **Java runtime used to run eclipse:** `1.8`
* **FeatureIDE Composer:** `Feature Modelling`

### Issue description
Using the .m format has some issues as follows:

- [ ] Parent features are automatically changed from concrete to abstract
- [ ] Saving the editor removes a char in the comment of the first line, ultimately making the editor crash

The exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at de.ovgu.featureide.fm.core.io.guidsl.GuidslReader.readModelData(GuidslReader.java:164)
	at de.ovgu.featureide.fm.core.io.guidsl.GuidslReader.parseInputStream(GuidslReader.java:122)
	at de.ovgu.featureide.fm.core.io.guidsl.GuidslFormat.read(GuidslFormat.java:45)
	at de.ovgu.featureide.fm.core.io.guidsl.GuidslFormat.read(GuidslFormat.java:1)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.checkModel(FeatureModelEditor.java:660)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.createPages(FeatureModelEditor.java:407)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:351)

The model file I used:
SPL : BASE___ [STATES___] [UNDO___] [COLOR___] [SOLVER___] [GENERATOR___] [EXTENDEDSUDOKU___] :: _SPL ;

%% // constraints
UNDO___ implies STATES___ ;
GENERATOR___ implies SOLVER___ ;
SOLVER___ implies UNDO___ ;

![FeatureIDEBUG3](https://user-images.githubusercontent.com/1482595/54158190-2e137e00-4407-11e9-8fe7-10fcfbff0f18.gif)

**Comment by tthuem** [comment]
As GUIDSL forces that every compound feature is abstract and every primitive is concrete, we cannot do much about the first problem. The second issue should be easy to fix.
