### ISSUE TITLE
Unhandled event loop exception when editing code highlighted by color scheme

### ISSUE THREAD

**Issue by PaulWestphal** [FeatureIDE/FeatureIDE#890]
Currently, on the develop and release 3.5 branches there is an unhandled event loop exception when editing code that is highlighted by the current color scheme. 

So far the only reliable way to reproduce is bug is fixing the code in step 5 of HandsOn5. It does not seem to occur if you skip steps 1-4 and try to immediately do step 5.

> org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:96)
	at org.eclipse.jface.text.Position.setLength(Position.java:181)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.doPaint1(AnnotationRulerColumn.java:793)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.doubleBufferPaint(AnnotationRulerColumn.java:557)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.redraw(AnnotationRulerColumn.java:865)
	at org.eclipse.jface.text.source.AnnotationRulerColumn$9.run(AnnotationRulerColumn.java:851)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3537)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)

**Comment by Subaro** [comment]
The issue does occur because the colo operation requires a valid ``ObjectUndoContext``. The context is only created when the feature model is copied, overwritten or opened in the feature model editor. The context which is created by the feature model editor is used for actions that mainly operate in the editor itself. When working with the HandsOn it is possible that the feature model editor wasn`t opened before. Resulting in the error shown above. 

As a hotfix we check that the feature model provides a valid context before executing the action with undo/redo functionality. 

A much better approach is to provide a valid context when the feature model is loaded by the feature model manager without the necessarity of the feature model editor beging opened before.

**Comment by Subaro** [comment]
@skrieter Do you have any idea how we can create such a context without affecting the standalone FeatureIDE Library?

**Comment by Subaro** [comment]
I tried to add the following lines at the end of the `FeatureProject` constructor:

```
final ObjectUndoContext undoContext = new ObjectUndoContext(getFeatureModel());
getFeatureModel().setUndoContext(undoContext);
```

Does eclipse need something like an eclipse editor to perform undo/redo operations. Because when i execute the operation the the two lines above everything works fine, except that no undo operation is executed when clicking STRG+Z

**Comment by Subaro** [comment]
We decided that my hotfix is sufficient for the issue. The hotfix disables undo and redo actions when the context is not available. When the context is available it is still possible to undo action even in the source code editor.
