### ISSUE TITLE
NullPointer when opening the feature model slice wizard

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#900]
### Issue description
When opening the feature model slice wizard via right-click on feature model -> Slice feature model the following error message is thrown:

```
org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:161)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
Caused by: java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.handlers.FeatureModelSlicingHandler.singleAction(FeatureModelSlicingHandler.java:52)
	at de.ovgu.featureide.fm.ui.handlers.base.AFileHandler.singleAction(AFileHandler.java:43)
	at de.ovgu.featureide.fm.ui.handlers.base.ASelectionHandler.execute(ASelectionHandler.java:53)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 37 more
```

**Comment by Subaro** [comment]
I fixed the null pointer. The wizard tried to load the feature model manager of the project path and not of the selected model.xml path, therefore, we changed the path and the wizards opens without any problems.

@skrieter 
Sometimes when we try to slice a feature model then the following issue appears:
```
java.lang.ArrayIndexOutOfBoundsException: 10
	at org.sat4j.minisat.orders.RSATPhaseSelectionStrategy.assignLiteral(RSATPhaseSelectionStrategy.java:49)
	at org.sat4j.minisat.orders.VarOrderHeap.assignLiteral(VarOrderHeap.java:236)
	at org.sat4j.minisat.core.Solver.propagate(Solver.java:1054)
	at org.sat4j.minisat.core.Solver.isSatisfiable(Solver.java:1940)
	at de.ovgu.featureide.fm.core.analysis.cnf.solver.SimpleSatSolver.hasSolution(SimpleSatSolver.java:172)
	at de.ovgu.featureide.fm.core.analysis.cnf.solver.SimpleSatSolver.hasSolution(SimpleSatSolver.java:185)
	at de.ovgu.featureide.fm.core.job.SliceFeatureModel.merge(SliceFeatureModel.java:276)
	at de.ovgu.featureide.fm.core.job.SliceFeatureModel.execute(SliceFeatureModel.java:79)
	at de.ovgu.featureide.fm.core.job.SliceFeatureModel.execute(SliceFeatureModel.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:44)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:122)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

You can reproduce the error with the following steps:
1. Load example Feature Modelling > Extended Feature Models > Sandwitch
2. Right-click the model.xml and select `Slice Feature Model`
3. In the Wizard select the feature `Sandwitch` and `Bread`
4. Click `Finish`. The wizard closes and the error is thrown.

Note: It seems the error is thrown when selecting a features which are in any transitive parent-children relation. When selecting only two sibling no error is thrown. But also then the generated model from the wizard contains the exact copy of the sliced model. So it seems the slicing is generally having some problems.

**Comment by PaulWestphal** [comment]
The null pointer exception does not occur in FeatureIDE 3.5.5, it seems like the bug was introduced in 3.6.0.
