### ISSUE TITLE
Large example feature models cannot be opened with recent FeatureIDE versions because of the outline view

### ISSUE THREAD

**Issue by tthuem** [FeatureIDE/FeatureIDE#923]
#### Prerequisitives
* **Eclipse Version:**  see release packages
* **FeatureIDE-Version:**  v3.6.1 and v3.5.5 (works with v3.4.3)
* **Operating system:** Windows 10
* **Java runtime used to run eclipse:** Java 8 Update 201

### Issue description
When opening Automotive02_V4 example feature model with v3.5.5 the UI freezes for a long long time and I had to kill the Eclipse after more than 10 minutes.

When opening Linux_2.6.33.3 example feature model with v3.6.1 I got an out of memory error in the error log:

```
eclipse.buildId=4.13.0.I20190916-1045
java.version=1.8.0_201
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.equinox.event
Error
Tue Nov 26 20:00:53 CET 2019
Exception while dispatching event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/ElementContainer/selectedElement/SET] {ChangedElement=org.eclipse.e4.primaryDataStack=org.eclipse.e4.ui.model.application.ui.basic.impl.PartStackImpl@32a72c4 (tags: [org.eclipse.e4.primaryDataStack, EditorStack], contributorURI: null) (widget: CTabFolder {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer@5bc14211, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null), Widget=CTabFolder {}, org.eclipse.e4.data={ChangedElement=org.eclipse.e4.primaryDataStack=org.eclipse.e4.ui.model.application.ui.basic.impl.PartStackImpl@32a72c4 (tags: [org.eclipse.e4.primaryDataStack, EditorStack], contributorURI: null) (widget: CTabFolder {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer@5bc14211, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null), AttName=selectedElement, EventType=SET, Widget=CTabFolder {}, NewValue=org.eclipse.e4.ui.compatibility.editor=org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl@2b8ad0d9 (tags: [Editor, removeOnHide, de.ovgu.featureide.fm.ui.editors.FeatureModelEditor], contributorURI: null) (widget: ContributedPartRenderer$1 {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer@345af277, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor, object: null, context: PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide de.ovgu.featureide.fm.ui.editors.FeatureModelEditorContext, variables: [], label: null, iconURI: null, tooltip: null, dirty: false, closeable: true, description: null)}, AttName=selectedElement, NewValue=org.eclipse.e4.ui.compatibility.editor=org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl@2b8ad0d9 (tags: [Editor, removeOnHide, de.ovgu.featureide.fm.ui.editors.FeatureModelEditor], contributorURI: null) (widget: ContributedPartRenderer$1 {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer@345af277, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor, object: null, context: PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide de.ovgu.featureide.fm.ui.editors.FeatureModelEditorContext, variables: [], label: null, iconURI: null, tooltip: null, dirty: false, closeable: true, description: null), EventType=SET} to handler org.eclipse.e4.ui.services.internal.events.UIEventHandler@35df5961

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(Unknown Source)
	at java.util.HashMap.putVal(Unknown Source)
	at java.util.HashMap.put(Unknown Source)
	at java.util.HashSet.add(Unknown Source)
	at org.prop4j.Node.buildCNF_rec(Node.java:277)
	at org.prop4j.Node.buildCNF_rec(Node.java:198)
	at org.prop4j.Node.buildCNF_rec(Node.java:198)
	at org.prop4j.Node.buildCNF_rec(Node.java:198)
	at org.prop4j.Node.buildCNF_rec(Node.java:198)
	at org.prop4j.Node.buildCNF_rec(Node.java:288)
	at org.prop4j.Node.buildCNF(Node.java:137)
	at de.ovgu.featureide.fm.core.analysis.cnf.Nodes.getClauseFromNode(Nodes.java:160)
	at de.ovgu.featureide.fm.core.analysis.cnf.Nodes.convert(Nodes.java:57)
	at de.ovgu.featureide.fm.core.analysis.cnf.Nodes.convert(Nodes.java:52)
	at de.ovgu.featureide.fm.core.AnalysesCollection$AConstraintAnalysisWrapper.setClauseGroups(AnalysesCollection.java:355)
	at de.ovgu.featureide.fm.core.AnalysesCollection$CauseAnalysisWrapper.setFormula(AnalysesCollection.java:265)
	at de.ovgu.featureide.fm.core.AnalysesCollection.init(AnalysesCollection.java:456)
	at de.ovgu.featureide.fm.core.FeatureModelAnalyzer.<init>(FeatureModelAnalyzer.java:99)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.FMAnalyzerCreator.create(FMAnalyzerCreator.java:34)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.FMAnalyzerCreator.create(FMAnalyzerCreator.java:1)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.ACreator.get(ACreator.java:41)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.FeatureModelFormula.getElement(FeatureModelFormula.java:60)
	at de.ovgu.featureide.fm.core.analysis.cnf.formula.FeatureModelFormula.getAnalyzer(FeatureModelFormula.java:105)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.createModelFileMarkers(FeatureModelEditor.java:541)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.setInput(FeatureModelEditor.java:510)
	at org.eclipse.ui.part.MultiPageEditorPart.init(MultiPageEditorPart.java:753)
	at de.ovgu.featureide.fm.ui.editors.FeatureModelEditor.init(FeatureModelEditor.java:134)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:353)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:340)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
```

Opening Automotive02_V4 with v3.4.3 works just fine.

**Comment by tthuem** [comment]
Closing both, the FeatureIDE outline and the Eclipse outline helped. Then, I was able to collapse all features to get a reasonable efficiency.

**Comment by SundermannC** [comment]
#1004 immensely reduced redundant updates of the outline view. It seems like the performance problem of the outline view is resolved. We still keep an eye on the impact of the outline view.

**Comment by tthuem** [comment]
No, it is not resolved in v3.7.1. FeatureIDE freezes at least for 10 minutes when opening the Linux model while the outlines are open:

![image](https://user-images.githubusercontent.com/5330357/120804252-b9c3d880-c544-11eb-8ba1-c06a736ccf30.png)

**Comment by tthuem** [comment]
Additionally, the job Updating Feature Model Edits will never terminate and cannot be cancelled. The job is started when opening the Feature Model Edits view.

**Comment by ekuiter** [comment]
![grafik](https://user-images.githubusercontent.com/4258713/127497585-ccd0227a-80e0-45fe-a39f-e9feef1f11f0.png)

For me, it happens even with the outline view and all other FeatureIDE views closed (FeatureIDE 3.7.2 prepackaged Windows, opening Linux 2.6.33).

**Comment by tthuem** [comment]
We decided to completely replace the outline for feature models. The idea is to rather present information on the changes applied to the current feature model.
