### ISSUE TITLE
Cannot delete multiple features at once

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#935]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.6`

### Issue description
It is not possible to delete multiple features. 

### Reproduce:
Select two siblings and hit Delete.
or
Select features with children => select subtree => Delete.

The following errors appear:

```
java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.MandatoryAction.selectionContainsOptionalFeature(MandatoryAction.java:54)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.MandatoryAction.updateProperties(MandatoryAction.java:68)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.MultipleSelectionAction.selectionElementChanged(MultipleSelectionAction.java:136)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.MultipleSelectionAction$1.selectionChanged(MultipleSelectionAction.java:58)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.fireSelectionChanged(AbstractEditPartViewer.java:247)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer$1.run(AbstractEditPartViewer.java:131)
	at org.eclipse.gef.SelectionManager.fireSelectionChanged(SelectionManager.java:156)
	at org.eclipse.gef.SelectionManager.deselect(SelectionManager.java:126)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.deselect(AbstractEditPartViewer.java:202)
	at org.eclipse.gef.editparts.AbstractEditPart.removeNotify(AbstractEditPart.java:942)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.removeNotify(AbstractGraphicalEditPart.java:823)
	at org.eclipse.gef.editparts.AbstractEditPart.removeChild(AbstractEditPart.java:880)
	at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:793)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:726)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:644)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramViewer.reload(FeatureDiagramViewer.java:271)
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramEditor.propertyChange(FeatureDiagramEditor.java:749)
	at de.ovgu.featureide.fm.core.base.event.DefaultEventManager.callListener(DefaultEventManager.java:68)
	at de.ovgu.featureide.fm.core.base.event.DefaultEventManager.fireEvent(DefaultEventManager.java:62)
	at de.ovgu.featureide.fm.core.io.manager.AFileManager.fireEvent(AFileManager.java:256)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.fireEvent(AbstractFeatureModelOperation.java:96)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.execute(AbstractFeatureModelOperation.java:68)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.FeatureModelOperationWrapper.execute(FeatureModelOperationWrapper.java:86)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.FeatureModelOperationWrapper.run(FeatureModelOperationWrapper.java:46)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.DeleteAction.run(DeleteAction.java:82)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:93)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:161)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:305)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:579)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:648)
	at org.eclipse.e4.ui.bindings.keys.OutOfOrderListener.handleEvent(OutOfOrderListener.java:72)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1099)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1742)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5137)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:411)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4797)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:345)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2303)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3532)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)

```

**Comment by PaulWestphal** [comment]
The selected features *are* deleted. The visuals of the feature model editor are just messed up.

**Comment by PaulWestphal** [comment]
The NullPointerException is due to the selection still containing Features that have already been deleted.  I'm not sure how to fix this.
