### ISSUE TITLE
NullPointer when executing AdustModelToEditorSize

### ISSUE THREAD

**Issue by Subaro** [FeatureIDE/FeatureIDE#938]
#### Prerequisitives
* **FeatureIDE-Version:**  `3.6`

### Issue description
NullPointer is thrown when performing the `AdjustModelToEditorSize` button in the feature model editor.

### Error

```
java.lang.NullPointerException
	at de.ovgu.featureide.fm.ui.editors.FeatureDiagramViewer.isNodeOutOfSight(FeatureDiagramViewer.java:234)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AdjustModelToEditorSizeOperation.checkChildren(AdjustModelToEditorSizeOperation.java:105)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AdjustModelToEditorSizeOperation.operation(AdjustModelToEditorSizeOperation.java:63)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.firstOperation(AbstractFeatureModelOperation.java:60)
	at de.ovgu.featureide.fm.core.io.manager.AFileManager.processObject(AFileManager.java:303)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.AbstractFeatureModelOperation.execute(AbstractFeatureModelOperation.java:64)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.FeatureModelOperationWrapper.execute(FeatureModelOperationWrapper.java:86)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.operations.FeatureModelOperationWrapper.run(FeatureModelOperationWrapper.java:46)
	at de.ovgu.featureide.fm.ui.editors.featuremodel.actions.AdjustModelToEditorSizeAction.run(AdjustModelToEditorSizeAction.java:61)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)

```

**Comment by Subaro** [comment]
Tested again seems to work now. Could be a race condition. @PaulWestphal could you test as well?

**Comment by PaulWestphal** [comment]
Adjust model to editor size seems to work fine for me. I've tried the 3.6.0 release, the 3.5.5 release and the current release3.6 branch.

**Comment by Subaro** [comment]
It could also be potentially related to #940. Using the wrong CreatreFeatureOperation could have lead to missing features (NPE) which are used for the layout.
