### ISSUE TITLE
Generating T-wise configurations with "Product Generator" fails because of missing apache.commons

### ISSUE THREAD

**Issue by SundermannC** [FeatureIDE/FeatureIDE#983]
#### Prerequisitives
* **Eclipse Version:**  `4.12`
* **FeatureIDE-Version:**  `Release 3.6 pre-built version and release3.6 branch`
* **Operating system:** `Windows 10`

### Issue description
The library apache.commons.math seems to not be automatically Building t-wise configurations with any algorithm does not create any configurations and results in the following exception:

eclipse.buildId=4.12.0.I20190605-1800
java.version=1.8.0_232
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product

org.eclipse.core.jobs
Error
Mon Feb 24 16:10:07 CET 2020
An internal error occurred during: "Create Configurations 1".

java.lang.NoClassDefFoundError: org/apache/commons/math/util/MathUtils
	at no.sintef.ict.splcatool.CoveringArrayChvatal.generate2(CoveringArrayChvatal.java:161)
	at no.sintef.ict.splcatool.CoveringArrayChvatal.generate(CoveringArrayChvatal.java:52)
	at no.sintef.ict.splcatool.CoveringArrayChvatal.generate(CoveringArrayChvatal.java:60)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.SPLCAToolConfigurationGenerator.generate(SPLCAToolConfigurationGenerator.java:84)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:71)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:1)
	at de.ovgu.featureide.fm.core.analysis.cnf.analysis.AbstractAnalysis.execute(AbstractAnalysis.java:82)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:53)
	at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator.execute(ACNFConfigurationGenerator.java:105)
	at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator.execute(ACNFConfigurationGenerator.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:44)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:122)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math.util.MathUtils cannot be found by de.ovgu.featureide.fm.core_3.6.0.201908302227
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more

**Comment by jabiercoding** [comment]
It was not working for ICPL and Chvatal as they use the class SPLCAToolConfigurationGenerator which uses SPLCAT.jar

Adding in the `lib` folder `commons-math-2.2.jar` and adding it to the `de.ovgu.featureide.fm.core` project classpath fixes this issue. https://ftp.cixug.es/apache//commons/math/binaries/commons-math-2.2.zip  Unfortunately newer versions of apache commons math changed the package names and MathUtils does not even contain the needed method used in SPLCAT.jar.

**Comment by Subaro** [comment]
When I add the `commons-mat-2.2.jar` the error is fixed. Even when the newer version does not work, we could still just ship the 2.2 version and everything should be fine.

After adding the commons library the following algorithms work again: ICPL, Chvatal

However, when executing IncLing on any example I get the following error:

```
java.lang.ArrayIndexOutOfBoundsException: 73
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.PairWiseConfigurationGenerator.addRelation(PairWiseConfigurationGenerator.java:296)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.PairWiseConfigurationGenerator.findInvalid(PairWiseConfigurationGenerator.java:452)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.PairWiseConfigurationGenerator.generate(PairWiseConfigurationGenerator.java:837)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:71)
	at de.ovgu.featureide.fm.core.analysis.cnf.generator.configuration.AConfigurationGenerator.analyze(AConfigurationGenerator.java:1)
	at de.ovgu.featureide.fm.core.analysis.cnf.analysis.AbstractAnalysis.execute(AbstractAnalysis.java:82)
	at de.ovgu.featureide.fm.core.job.LongRunningWrapper.runMethod(LongRunningWrapper.java:53)
	at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator.execute(ACNFConfigurationGenerator.java:106)
	at de.ovgu.featureide.ui.actions.generator.configuration.ACNFConfigurationGenerator.execute(ACNFConfigurationGenerator.java:1)
	at de.ovgu.featureide.fm.core.job.Executer.execute(Executer.java:44)
	at de.ovgu.featureide.fm.core.job.LongRunningJob.work(LongRunningJob.java:48)
	at de.ovgu.featureide.fm.core.job.AbstractJob.run(AbstractJob.java:122)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

```

**Comment by Subaro** [comment]
FeatureIDE License: 
```
GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
```
Apache Commons Math 2.2 License:
```
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/
```

Compatibility between both (source: https://www.apache.org/licenses/GPL-compatibility.html):
```
The Free Software Foundation considers the Apache License, Version 2.0 to be a free software license, compatible with version 3 of the GPL. The Software Freedom Law Center provides practical advice for developers about including permissively licensed source.

Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

This licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.

We avoid GPLv3 software because merely linking to it is considered by the GPLv3 authors to create a derivative work. We want to honor their license. Unless GPLv3 licensors relax this interpretation of their own license regarding linking, our licensing philosophies are fundamentally incompatible. This is an identical issue for both GPLv2 and GPLv3.
```

**Comment by Subaro** [comment]
Bug was introduced in f8a3675 as the plugin reference from apache.commons.math was removed.

**Comment by Subaro** [comment]
Fix (pull request) was is merged #1030

**Comment by Subaro** [comment]
Fix: ebeda36 & Pull Request: d2377c5

**Comment by Subaro** [comment]
Apparently is the apach.commons.math no longer available as a plugin for newer eclipse versions. Should we stay on a functional eclipse version or use the newer versions and shift the responsibility to the users for providing a functional apache.commons jar?

**Comment by h3ssto** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471077

**Comment by h3ssto** [comment]
org.apache.commons.math3 is part of Eclipse Orbit, so they should not be any legal issues when adding its jar to FeatureIDE

**Comment by Subaro** [comment]
I think their bug is not related. First, the report is quite old. Second, we need apache 2.X, not apache 3.X. Sadly I didn't find any information about the missing apache.commons plugins. Maybe the apache.commons is not updated for the newest eclipse plugin

**Comment by h3ssto** [comment]
I see, well it was worth a try, as I stumbled over it yesterday.
